### ISSUE TITLE
How to bundle the pre-compiled libraries for audio-only?

### ISSUE THREAD

**Issue by tinsukE** [wseemann/FFmpegMediaMetadataRetriever#100]
I intend to use the library to get the currently playing song title for SHOUTcast and Icecast streams only, but I don't want to bundle the whole shebang.

libavcodec.so and libavformat.so seem to be the biggest dependencies one would want to get rid of.

Anyway to get only the needed libraries as a gradle dependency?

**Comment by wseemann** [comment]
I'm not sure what you are asking. Everything that is compiled with the library is needed to retrieve even basic metadata, it can't be broken out.
