### ISSUE TITLE
App froce clases, help me!

### ISSUE THREAD

**Issue by xperiafan13-rom** [wseemann/FFmpegMediaMetadataRetriever#104]
Hello im try your library, i follow this;
import to android studio
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.10'

add FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever(); to my activity
but when I run my application , this closes
me missing some step?
   If so , could you explain me , I did wrong?

**Comment by wseemann** [comment]
What is the crash you are receiving?

**Comment by xperiafan13-rom** [comment]
This is difficult , because not give me any Log

**Comment by xperiafan13-rom** [comment]
![log](https://cloud.githubusercontent.com/assets/6379241/16534587/6808786a-3fd0-11e6-8f42-476ec23d92f6.png)

**Comment by wseemann** [comment]
This log doesn't help me. The crash will produce an exception that will be logged.

**Comment by xperiafan13-rom** [comment]
Already fixed in new version, thanks!!!
