### ISSUE TITLE
how can I get the size of the video?

### ISSUE THREAD

**Issue by halfking** [wseemann/FFmpegMediaMetadataRetriever#105]
It's good to use.
can you add some function like this:
1. retreive the size of video from meta data.
2. reverse video with ffmpeg?

thanks a lot.

**Comment by wseemann** [comment]
You can retrieve the with [METADATA_KEY_FILESIZE](http://wseemann.github.io/FFmpegMediaMetadataRetriever/apidocs/wseemann/media/FFmpegMediaMetadataRetriever.html#METADATA_KEY_FILESIZE). #2 is outside the scope of this project.
