### ISSUE TITLE
OpenSSL lower then 1.02f/1.01r

### ISSUE THREAD

**Issue by ThoughtPT** [wseemann/FFmpegMediaMetadataRetriever#106]
Im getting a reject to a app submit, because of openSSL
https://support.google.com/faqs/answer/6376725

I belive it is because of this library.
does this uses a old version of OpenSSL ?

im using [Prebuilt AARs with HTTPS](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/download/v1.0.9/prebuilt-aars-with-https.zip)

**Comment by fxpage** [comment]
@wseemann any solution yet?

**Comment by tufyx** [comment]
@wseemann I think this is an important issue to tackle. Apps are getting rejected from the Android PlayStore because of this incompatibility

**Comment by wseemann** [comment]
This is fixed in the [latest release](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/latest).
