### ISSUE TITLE
Can not get the bitrate of the video

### ISSUE THREAD

**Issue by kingty** [wseemann/FFmpegMediaMetadataRetriever#108]
get null

**Comment by wseemann** [comment]
This is a terrible bug report. You didn't supply any way to debug your issue. I need a sample video or URL to test with.

**Comment by kingty** [comment]
mmm,sorry for that .I mean any video I film by android phone ,it can not get the bitrate of the video   by the method 
`fmRetriever.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_VARIANT_BITRATE)+"")`
 it always get null

**Comment by wseemann** [comment]
Again: "I need a sample video or URL to test with.". Please post a video I can test with.

**Comment by wseemann** [comment]
Closed due to inactivity.
