### ISSUE TITLE
Gennymotion API 19 Crash

### ISSUE THREAD

**Issue by Hackmodford** [wseemann/FFmpegMediaMetadataRetriever#109]
Setting the datasource in a API 19 Genymotion emulator causes an immediate crash.

There isn't much to go on in the log.

```
08-21 12:47:18.660 I/MediaMetadataRetrieverJNI: native_init
08-21 12:47:18.660 I/MediaMetadataRetrieverJNI: native_setup
08-21 12:47:18.660 V/MediaMetadataRetrieverJNI: setDataSource
08-21 12:47:18.776 A/libc: Fatal signal 11 (SIGSEGV) at 0xffffffff (code=1), thread 1357 (AsyncTask #2)
```

**Comment by cinder92** [comment]
same issue here

**Comment by HBiSoft** [comment]
It's a emulator. It would be expected to have issues that doesn't appear on a real device.

**Comment by wseemann** [comment]
Closing out this ticket due to age. Please file a new issue of this issue is still relevant and persists.
