### ISSUE TITLE
Is HLS stream (.m3u8) supported?

### ISSUE THREAD

**Issue by brystel** [wseemann/FFmpegMediaMetadataRetriever#11]
<b>
Hello,
I'm trying to play HLS stream. I'm using demo example and I have problems with getFrames from almost all streams. Please notice, that some streams are in HD res.
For example the only working stream is: </b>

http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8
<b>
When I trying to get frame from:</b>
"http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8<b>
I get error:</b>
03-04 11:59:06.320: A/libc(1516): Fatal signal 11 (SIGSEGV) at 0x00000004 (code=1), thread 1562 (ModernAsyncTask)

<b>Then I create simple function from library usage sample code I get following errors:</b>

03-04 12:46:24.139: E/AndroidRuntime(22177): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.firstframetest/com.example.firstframetest.MainActivity}: java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2097)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.app.ActivityThread.access$600(ActivityThread.java:140)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.os.Handler.dispatchMessage(Handler.java:99)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.os.Looper.loop(Looper.java:137)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.app.ActivityThread.main(ActivityThread.java:4895)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at java.lang.reflect.Method.invokeNative(Native Method)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at java.lang.reflect.Method.invoke(Method.java:511)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at dalvik.system.NativeStart.main(Native Method)
03-04 12:46:24.139: E/AndroidRuntime(22177): Caused by: java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF
03-04 12:46:24.139: E/AndroidRuntime(22177):    at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(Native Method)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at com.example.firstframetest.MainActivity.onCreate(MainActivity.java:21)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.app.Activity.performCreate(Activity.java:5163)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
03-04 12:46:24.139: E/AndroidRuntime(22177):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2061)
03-04 12:46:24.139: E/AndroidRuntime(22177):    ... 11 more

**Comment by drawf** [comment]
@wseemann 
Can you give a support for HLS demo? thank you very much indeed

**Comment by forfiter9** [comment]
is there maybe any example for this one using the Java playlist parser?
