### ISSUE TITLE
How to improve efficiency

### ISSUE THREAD

**Issue by nicklemay** [wseemann/FFmpegMediaMetadataRetriever#110]
I hava test the efficiency in my project,it cost nearly 1s to show the thumbnail,is there any solution I can take to improve the efficiency,please help me if you can,thanks!

**Comment by wseemann** [comment]
How are you using the library? Simply posting the time it takes isn't enough issue to determine what might be causing any potential latency. Please post a code snippet.

**Comment by wseemann** [comment]
Closed due to inactivity.
