### ISSUE TITLE
Video creation time coming null

### ISSUE THREAD

**Issue by sandeep-agrawal** [wseemann/FFmpegMediaMetadataRetriever#111]
I am tyring to get the video created time using  mediaMetadataRetriever.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_CREATION_TIME); but it is coming null.

**Comment by wseemann** [comment]
Can you post a sample video I can test with?

**Comment by wseemann** [comment]
Closed due to inactivity.
