### ISSUE TITLE
FFmpegMediaMetadataRetriever.setDataSource IllegalArgumentException

### ISSUE THREAD

**Issue by ChernyshovYuriy** [wseemann/FFmpegMediaMetadataRetriever#112]
JavaDoc for the provided method saying:
IllegalArgumentException If the path is invalid
However, provided URL is valid and playable. For example:
http://prclive1.listenon.in:9948/
http://str0.creacast.com:80/radio_coquelicot
http://us1.internet-radio.com:8476/stream
I understand that could be different reasons for the error while extracting metadata, but it is definitely not invalid path.
Would be nice to have some detailed information with exception rather then status = 0xFFFFFFFF.
I tested those streams on VLC player prior to post this issue.
Thanks a lot in advance and thanks for the library!

**Comment by wseemann** [comment]
All three URL's worked for me using the current version.

**Comment by ChernyshovYuriy** [comment]
Can you post code example that you use?
U do use:

```
FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
mmr.setDataSource("http://prclive1.listenon.in:9948/");
FFmpegMediaMetadataRetriever.Metadata md = mmr.getMetadata();
Map<String, String > map = md.getAll();
if (map != null) {
    for (final String key : map.keySet()) {
        Log.d("MainActivity", "Key:" + key + " Val:" + map.get(key));
    }
}
mmr.release();
```

And result is:

```
Exception:setDataSource failed: status = 0xFFFFFFFF
```

**Comment by ChernyshovYuriy** [comment]
Closing this issue, switched to the ExoPlayer and able to get metadata from it. Sorry.
