### ISSUE TITLE
error in ".setDataSource(MainActivity.this, uri);" in Android 5.0

### ISSUE THREAD

**Issue by maksimsukalov** [wseemann/FFmpegMediaMetadataRetriever#113]
When I pick the video file and press button for convert it to GIF - I get "App has been stopped".

The error is specify to ".setDataSource(MainActivity.this, uri);" in this part of code:

`fFmpegMediaMetadataRetriever = new FFmpegMediaMetadataRetriever();
fFmpegMediaMetadataRetriever.setDataSource(MainActivity.this, uri);`

In Andoid 4 and 6 it's working well.

First photo is a log, second - crashlytics.

As I understand, error in JNI library, right? How to fix this error?

![log](https://cloud.githubusercontent.com/assets/16764855/18608119/0f1fa182-7ce9-11e6-8974-1aa9b00875f2.JPG)

![default](https://cloud.githubusercontent.com/assets/16764855/18608121/26dc3ede-7ce9-11e6-8528-e566fbf5bf10.JPG)

**Comment by erehmi** [comment]
+1

**Comment by zivids** [comment]
+1

**Comment by HBiSoft** [comment]
Why use context and Uri. Just pass that path to the file as a string.

**Comment by Hackmodford** [comment]
I am getting a sigbart -6

Using the context and uri gives me the error
Using just the path gives me the error
Removing whitespaces from path (in both cases) still gives error

Only reverting to 1.0.10 resolves the issue. Problem is, that version doesn't have 64 bit support.

**Comment by wseemann** [comment]
Closing out this ticket due to the low number of devices still running Android 5.0 . Please file a new issue of this issue is still relevant and persists.
