### ISSUE TITLE
 Rmvb Video The result obtained using the getFrameAtTime () method is a black screen

### ISSUE THREAD

**Issue by biezhihua** [wseemann/FFmpegMediaMetadataRetriever#116]
Rmvb Video The result obtained using the getFrameAtTime () method is a black screen.

Please,Is there any good solution？

**Comment by biezhihua** [comment]
The problem has been fixed, but not perfect。

The reason is that a frame needs rmvb before and after the connection

My modify a part of code.

```
// Decode video frame
if (avcodec_decode_video2(state->video_st->codec, frame, got_frame, pkt) <= 0) {
	*got_frame = 0;
	// break; // me modify
        // When decoding errors continue to retrieve
}
```

**Comment by wseemann** [comment]
Closing out this ticket due to age . Please file a new issue of this issue is still relevant and persists.
