### ISSUE TITLE
API 23 Crash

### ISSUE THREAD

**Issue by hsy402** [wseemann/FFmpegMediaMetadataRetriever#118]
First of all, thanks for your library.

It works well in API 21. (Android 5.0, Galaxy Note3)
but, unfortunately it doesn't work in API 23. (Android 6.0.1, Galaxy S6)

please check these logs.
warning logs in API 21. so, no problem here.

**10-14 15:40:20.696 13808-13808/com.test.sample W/art: Failed to find OatDexFile for DexFile /data/data/com.test.sample/files/instant-run/dex/slice-slice_4-classes.dex ( canonical path /data/data/com.test.sample/files/instant-run/dex/slice-slice_4-classes.dex) with checksum 0xdaea03c5 in OatFile /data/data/com.test.sample/cache/slice-slice_4-classes.dex
10-14 15:40:22.726 13808-13808/com.test.sample W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable**

When I run my app, 
fatal exception logs in API 23, this is crash.

**10-14 18:56:53.312 32499-32499/com.test.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.test.sample, PID: 32499
                                                                      java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.test.sample/files/instant-run/dex/slice-support-annotations-24.2.1_719570978a6c9772713556f84375c45cf375e98c-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-internal_impl-24.2.1_e9cc135fa4f7ea1fb6136a0203beea52674642db-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-internal_impl-24.2.1_77fdbe7f377829460d5caa4915a56267ffb4e029-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-internal_impl-24.2.0_621275fbd4d2cf9c00296a1302768558600c24f5-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-internal_impl-24.2.0_35077370de00fa07e986b8e7be718708b7be0e7d-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-internal_impl-24.2.0_2d2d9880084b32a529d71bd3ed16e25a3f5988ba-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-commons-lang3-3.4_a52b92299f962531e24dd44615ac3630a19de028-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-commons-io-2.5_5ecc072893dd6355eb42e551afdff15e47f04372-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.jakewharton-butterknife-8.4.0_0a874cb685d981d0b76c8f1c0774220580386400-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.github.wseemann-FFmpegMediaMetadataRetriever-1.0.11_795b67eb9a8da75bd9a86390a3d01b875a5e764e-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.facebook.fresco-imagepipeline-base-0.14.1_e45305e9fd2ea70caf979d8524e805b679b93e0f-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.facebook.fresco-imagepipeline-0.14.1_598900fc6c73bf7ffa9170c1b0af7198da0f4d97-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.facebook.fresco-fresco-0.14.1_f5b9defb44648f1f005133d4f5406a5ffd70c0f7-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.facebook.fresco-fbcore-0.14.1_bea347a387ec52eb37110b4dbd467a207d39d5a6-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.facebook.fresco-drawee-0.14.1_3e9a243fee7c663b85fccdac991ebeaba1d2583c-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.facebook.fresco-animated-gif-0.14.1_09d6c53a9c4dfbbb319fd6c6c398a93aaa961f9c-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.facebook.fresco-animated-base-0.14.1_e9c4125c173d9c0578398ffba20e57b18296f22d-classes.dex", dex file "/data/data/com.test.sample/files/instant-run/dex/slice-com.android.support-support-vector-drawable-24.2.0_36848a810a13f9ed**

please any advice.
Thank you.

**Comment by hsy402** [comment]
no copied ffmpeg so lib in arm64-v8a dir..
unlike armeabi dir(apk's lib dir)

**Comment by hsy402** [comment]
Thank you !!

**Comment by YGDroid** [comment]
i cannot find arm64-v8a libs in prebuild-aars.zip now.
i downloaded 0.12 ver.

please check more.

**Comment by wseemann** [comment]
That's because they aren't in there. I added support for them to be built
but I didn't build them in this release.
