### ISSUE TITLE
Native FC

### ISSUE THREAD

**Issue by JoyHong** [wseemann/FFmpegMediaMetadataRetriever#119]
Hey guy
i'm using latest version 1,0.11, but when run at setDataSource, it's FC
could u please help me to have a check?

10-16 19:37:26.564 5233-5263/com.example.demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1 in tid 5263 (AsyncTask #1)
10-16 19:37:26.654 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.654 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.655 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.655 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.655 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.655 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.656 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.656 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.656 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.657 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.657 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.657 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.657 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.658 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.658 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.658 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.659 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.659 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.659 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.659 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.660 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.660 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.660 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.660 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.661 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.661 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.661 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.662 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.662 5280-5280/? E/AEE/LIBAEE: aee_ioctl_get_reg: open device failed, No such file or directory
10-16 19:37:26.781 850-1178/? E/HsmCoreServiceImpl: onTransact in code is: 102
10-16 19:37:27.147 850-869/? E/PROXIMITY: ProximitySensor: unknown event (type=3, code=0)
10-16 19:37:27.435 850-850/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 19 num clients 9
10-16 19:37:27.436 850-850/? E/WifiTrafficPoller:  packet count Tx=560 Rx=521
10-16 19:37:27.547 850-869/? E/PROXIMITY: ProximitySensor: unknown event (type=3, code=0)
10-16 19:37:27.747 850-869/? E/PROXIMITY: ProximitySensor: unknown event (type=3, code=0)
10-16 19:37:27.947 850-869/? E/PROXIMITY: ProximitySensor: unknown event (type=3, code=0)
10-16 19:37:28.147 850-869/? E/PROXIMITY: ProximitySensor: unknown event (type=3, code=0)

**Comment by wseemann** [comment]
Can you supply more details on the crash? I don't see anything in the output related to this library.

**Comment by wseemann** [comment]
Closed due to inactivity.
