### ISSUE TITLE
The format is ape can not be resolved !!!!

### ISSUE THREAD

**Issue by zhangchaojiong** [wseemann/FFmpegMediaMetadataRetriever#121]
```
String artists_name = mmr
					.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ARTIST);
```
artists_name  is null.

**Comment by wseemann** [comment]
This is not enough information to debug the issue. Please include the URL or sample file you are using to test.

**Comment by zhangchaojiong** [comment]
[testFile.txt](https://github.com/wseemann/FFmpegMediaMetadataRetriever/files/546888/testFile.txt)

> 1.This is an audio file, change the .txt to .zip and unzip it.
> 2.Put this audio file in the sd card, and then get a path

my code:
```
FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
mmr.setDataSource(path);// This variable--path, is the path to the audio in the SD card .
String artists_name = mmr
                    .extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ARTIST);
String  song_name = mmr
		.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_TITLE);
int duration = Integer.parseInt(mmr
				.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION));
```
Debug results:
artists_name is null.
song_name  is null.
duration is normal




> I am sorry, I English is not good, most of them come from Google translation

**Comment by wseemann** [comment]
This file doesn't contain the metadata you are trying to retrieve.
<img width="788" alt="screen shot 2016-10-23 at 10 31 15 pm" src="https://cloud.githubusercontent.com/assets/2296196/19632850/862ca010-9970-11e6-8a76-05005a2e4d6e.png">

**Comment by zhangchaojiong** [comment]
> I can see that the value of the artist variable is "Candee Jay"
> However, I use the following method:

```
String artists_name = mmr
                    .extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ARTIST);
```

> Why do I get the value is null

**Comment by zhangchaojiong** [comment]
I saw in your screenshot: 

> artist: Candee Jay

Why I can not get this value？

**Comment by wseemann** [comment]
Use key "Artist", not |METADATA_KEY_ARTIST.|

**Comment by wseemann** [comment]
I already replied with the solution.

**Comment by zhangchaojiong** [comment]
> Good job, thank you !

>  But I have a suggestion: key-values should be case-insensitive.`

**Comment by zhangchaojiong** [comment]
@wseemann

> Good job, thank you !
> But I have a suggestion: key-values should be case-insensitive.`
