### ISSUE TITLE
1.0.12 version build failed

### ISSUE THREAD

**Issue by hsy402** [wseemann/FFmpegMediaMetadataRetriever#122]
Thank you for your quick response.

I've just downloaded and tested new version (1.0.12)
but build failed.
please check these msg. Thank you.

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:transformNative_libsWithMergeJniLibsForDebug'.
  
  > com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libavcodec.so
  > File1: C:\Users\Naver\AndroidStudioProjects\TestPrj\app\build\intermediates\exploded-aar\com.github.wseemann\FFmpegMediaMetadataRetriever\1.0.12\jni
  > File2: C:\Users\Naver\AndroidStudioProjects\TestPrj\app\build\intermediates\exploded-aar\TestPrj\armv7-fmmr\unspecified\jni
- Try:
  Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

**Comment by wseemann** [comment]
Ensure instant run is disabled and use the same build tools as the one already defined in `build.gradle`.
