### ISSUE TITLE
1.0.12 is not working with gradle build

### ISSUE THREAD

**Issue by LiuLei030504** [wseemann/FFmpegMediaMetadataRetriever#124]
Hello,

Here is my gradle configuration for this library.
compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.12'

And I am getting error to initialise this class.

java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.biznessapps.layout/files/instant-run/dex/slice-twitter4j-core-4.0.2_eb4fdeb9ad593e54454cde7e9f7d440d5f32dd88-classes.dex", dex file "/data/data/com.biznessapps.layout/files/instant-run/dex/slice-support-annotations-24.2.1_bc4bcd0ef2a96696bc46c5d00c63b981dbe718d1-classes.dex", dex file "/data/data/com.biznessapps.layout/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.biznessapps.layout/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.biznessapps.layout/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.biznessapps.layout/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.biznessapps.layout/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.biznessapps.layout/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.biznessapps.layout/files/instant-run/dex/slice-s
	at java.lang.Runtime.loadLibrary0()(Runtime.java:972)
	at java.lang.System.loadLibrary()(System.java:1530)
	at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>()(FFmpegMediaMetadataRetriever.java:124)
	at com.biznessapps.player.PlayerServiceAccessor.getDuration()(PlayerServiceAccessor.java:99)
	at com.biznessapps.player.PlayerServiceAccessor.getDuration()(PlayerServiceAccessor.java:110)
...

Can you let me know how can I fix it?

Tested device: Nexus 6p, 7.0

**Comment by LiuLei030504** [comment]
I just found 1.0.12 does not support the arm64-v8a.
Can you confirm it and how can we solve it? Thanks

**Comment by wseemann** [comment]
Fixed in version 1.0.13.
