### ISSUE TITLE
efficiency issue

### ISSUE THREAD

**Issue by mehraf** [wseemann/FFmpegMediaMetadataRetriever#126]
Hi,
i'm using the library the to extract all the frames from the video

here is my code :

`        Thread t3 = new Thread(new Runnable() {
            @Override
            public void run() {
                FFmpegMediaMetadataRetriever mediaData = new FFmpegMediaMetadataRetriever();
                mediaData.setDataSource(Environment.getExternalStorageDirectory().getAbsolutePath() + "/myvid1.mp4");
             

                for (int i=0;i<2000;i++){
                    long cur = System.currentTimeMillis();
                    Bitmap frame = mediaData.getFrameAtTime(i*1000);
                   
                    cur = System.currentTimeMillis()-cur;
                    Log.d("BBB","Took"+cur);
                }
            }
        });
        t3.start();
`

result is ;
Took491
Took551
Took501
Took510
Took480
...

how can we improve efficiency in retrieving the frames since it takes a long time to get all the frames ?

**Comment by wseemann** [comment]
I think 500 or so milliseconds is efficient given what the library is doing.
