### ISSUE TITLE
slow motion on every camera streem

### ISSUE THREAD

**Issue by wisien92** [wseemann/FFmpegMediaMetadataRetriever#127]
Hi,

I started using your lib for displaying RTSP camera stream. When the stream is low resolution it works ok (at least it seems to be resolution or size problem). But with higher quality the video is extreme slow motion. 
perhaps I have done something wrong so I'll describe my setup.

I have created Runnable where at start I set up _FFmpegMediaMetadataRetriever_ and then I start my while loop. In loop I look for thread interruption to stop , release media retriever and exit loop. The bitmap is sent to fragment via interface week reference and added to ImageView in _runOnUIThread_ method. Is there something that I have done wrong or something to change/improve? 

Below is my code snippet:

    @Override
    public void run() {
		try {
			mediaRetriever = new FFmpegMediaMetadataRetriever();
			try {				
				mediaRetriever.setDataSource(url);
			} catch (IllegalArgumentException e) {
				// start failed behaviour
				return;
			}
			openCameraCommunication();
		} catch (Exception exception) {
			// failed behaviour
		}
	}

    private void openCameraCommunication() {
		while (true) {
			if (Thread.interrupted()) {
				Log.e(TAG, "Camera Thread interrupted.");
				stopMediaRetriever();
				return;
			}
			Bitmap imageBitmap = mediaRetriever.getFrameAtTime();
			if (imageBitmap != null && frameObtainedInterface.get() != null) {
				frameObtainedInterface.get().frameObtained(imageBitmap);
			}
		}
	}
`

PS: there is also isse when a lot of movement - then most of the frames are blurred.

PS2:using 1.0.13 but with 1.012 I had the same problem.

**Comment by wseemann** [comment]
Use a media player for what you are trying to accomplish. This library is not intended to render real time video streams.
