### ISSUE TITLE
APK size

### ISSUE THREAD

**Issue by daliz** [wseemann/FFmpegMediaMetadataRetriever#129]
Using the FFmpegMediaMetadataRetriever library, my APK size goes up by 20-25 MB. Is there a way to reduce this? Thanks.

**Comment by AlekseiBazhenov** [comment]
+1 
I have the same problem
http://prnt.sc/dfh2b8

**Comment by wseemann** [comment]
Use the prebuilt AARs included in the release section instead of the gradle
module. Generate individual APK's for each target architecture.

**Comment by daliz** [comment]
Thank you for your reply.
