### ISSUE TITLE
get same pictures  by using different time parameters

### ISSUE THREAD

**Issue by like001** [wseemann/FFmpegMediaMetadataRetriever#130]
Bitmap bitmap = null;
        FFmpegMediaMetadataRetriever retriever = null;
        try {
            retriever = new FFmpegMediaMetadataRetriever();
            retriever.setDataSource(filePath);
            bitmap = retriever.getFrameAtTime(shotTime,FFmpegMediaMetadataRetriever.OPTION_NEXT_SYNC);
        }

//As you can see,when the shotTime is different,I get the same picture when I compress thr bitmap to sdcard.I tried for many times and  several videos.

**Comment by wseemann** [comment]
Use `OPTION_CLOSEST` not `OPTION_NEXT_SYNC`.
