### ISSUE TITLE
how to change the architecture of supported?

### ISSUE THREAD

**Issue by jigeyisi** [wseemann/FFmpegMediaMetadataRetriever#133]
my project only support armv7 architecture, when i dependent your project ,it crashed. how can i do to solve it?

**Comment by ZhanRu** [comment]
defaultConfig {
        ...
        ndk {
            abiFilters "armeabi-v7a"
        }
    }

----------------------------------------------
o(*≧▽≦)ツ

**Comment by jigeyisi** [comment]
thanks
