### ISSUE TITLE
about frame retriever

### ISSUE THREAD

**Issue by Harryuan** [wseemann/FFmpegMediaMetadataRetriever#135]
Hi man,
does it support to get frame from the RTSP live stream?
like the rtsp://192.168.42.1/live
Many Thanks

**Comment by Harryuan** [comment]
one parameter of getFrameAtTime function is a timeUs,
but live stream seems to have no time length information

**Comment by wseemann** [comment]
The library supports RTSP, use [getFrameAtTime()](http://wseemann.github.io/FFmpegMediaMetadataRetriever/apidocs/wseemann/media/FFmpegMediaMetadataRetriever.html#getFrameAtTime()).
