### ISSUE TITLE
Fatal signal 11

### ISSUE THREAD

**Issue by nam1796** [wseemann/FFmpegMediaMetadataRetriever#138]
I tried to build the library(AAR file) and used the AAR. I always get crash.
fatal signal 11 at line: 497 file : ffmpeg_mediametadataretriever.c
It seems:  codecCtx is null.
Could you help me, how can i build AAR without crash ?

Thank you.

**Comment by wseemann** [comment]
How are you building the aar?

**Comment by wseemann** [comment]
Closed due to inactivity.
