### ISSUE TITLE
Build for generating thumbnails only

### ISSUE THREAD

**Issue by Farasy** [wseemann/FFmpegMediaMetadataRetriever#139]
Thanks for your work, William.

I'm using your lib to generate thumbnails for videos. Unfortunately, even with splitting different Abi's, the filesize of each apk increases about 3mb.
May you can create a build (especially for me 😃 ) that supports creating thumbnails but other stuff.
I don't know if it's possible. I would try it but i'm not on unix..

I appreciate!

**Comment by wseemann** [comment]
3mb is a negligible size increase in my opinion. Even if I were to remove
code from the library or optimize it to only retrieve thumbnails it's not
going to reduce the size by a noticeable degree.

**Comment by Farasy** [comment]
It is, absolutely. My goal is to keep the apk size of my apps as low as possible.
I thought there might by a noticeable degree by keeping unneeded code out of the build.

**Comment by wseemann** [comment]
Unfortunately, removing the code in question would not result in a noticeable decrease in your APK size.
