### ISSUE TITLE
Import library and use current build of ffmpeg

### ISSUE THREAD

**Issue by MattJakeman** [wseemann/FFmpegMediaMetadataRetriever#140]
I have a project that already uses ffmpeg and has the libraries built in. I am trying to import your library into my android studio project (that uses cmake for building the JNI parts) but haven't been able to go about it successfully. Do you have any pointers on how I can use your library with my current ffmpeg build?

**Comment by wseemann** [comment]
How are you currently importing the library?

**Comment by MattJakeman** [comment]
I tried earlier by importing via android studio - File->New->Import Module

I had to remove the apply from: 'maven-push.gradle' line from build.gradle but still couldn't get it to compile. I wasn't sure if this was the correct approach and had to abandon shortly after to work on another part of the project.

Would you recommend that as a starting point or is there a better approach?

**Comment by MattJakeman** [comment]
For reference, for anyone else attempting this, I got this working by pulling in src/main/java/wseemann/media/FFmpegMediaMetadataRetriever.java to package wseeman.media in my project.

I then pulled in all c, c++ and .h files from src/main/jni/metadata/ to my root level cpp directory.

I then modified my CMakeLists.txt file by adding the following parts:

`add_library(ffmpeg_mediametadataretriever_jni SHARED
            wseemann_media_MediaMetadataRetriever.cpp
            mediametadataretriever.cpp
            ffmpeg_mediametadataretriever.c
            ffmpeg_utils.c)

target_include_directories(ffmpeg_mediametadataretriever_jni PRIVATE
                           ${distribution_DIR}/ffmpeg/include)

target_link_libraries( ffmpeg_mediametadataretriever_jni
                       android
                       jnigraphics
                       libswresample
                       libavcodec
                       libavformat
                       libswscale
                       libavutil
                       log )`

I was then able to call methods from FFmpegMediaMetadataRetriever.java against my own ffmpeg libs.

**Comment by wseemann** [comment]
Perhaps try reading the documentation in the future. The `Using FMMR in your application (Android Studio)` section in the [README](https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/master/README.md) details how to import this library into your Android Studio project.
