### ISSUE TITLE
How to retriever to bitmap real time like instagram

### ISSUE THREAD

**Issue by kazixma** [wseemann/FFmpegMediaMetadataRetriever#141]
I want to do get cover video like instagram.

I use seekbar to choose frame for get bitmap and preview but it's not real time like instagram

How to do it.

Thank

**Comment by wseemann** [comment]
What do you mean by "it's not real time like". The library has to seek to the desired frame each time you move the seek bar, decode it and create a new bitmap. This is obviously a labor intensive task and may slow down your UI depending on what sort of work you are doing on the main thread.

**Comment by wseemann** [comment]
Closed due to inactivity.
