### ISSUE TITLE
java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFFF

### ISSUE THREAD

**Issue by sam16222** [wseemann/FFmpegMediaMetadataRetriever#143]
I am using an AssetFileDescriptor to play a video from from the assets folder of the application. The code is as follows:

AssetFileDescriptor afd;
try {
            afd = context.getContext().getAssets().openFd("tron.mp4");
            android.util.Log.d(TAG, "Assets was found.");
            mediaPlayer.setDataSource(afd.getFileDescriptor(), afd.getStartOffset(), afd.getLength());
            mmr.setDataSource(afd.getFileDescriptor());
            android.util.Log.d(TAG, "DataSource was set.");
            afd.close();
            mediaPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
                @Override
                public void onPrepared(MediaPlayer mp) {
                    Log.d(TAG, "onPrepared");
                    mediaPlayer.start();
                }
            });
            mediaPlayer.prepare();

        } catch (IOException e) {
            e.printStackTrace();
            android.util.Log.e(TAG, "Assets were not loaded. Stopping application!");
        }

The media Player works separately but with both the lines in the code, It crashes giving the setDataSource failed error. Can you help me out here?

**Comment by wseemann** [comment]
This bug report isn't related to my library.
