### ISSUE TITLE
FFmpegMediaMetadataRetriever 

### ISSUE THREAD

**Issue by luXiuKun** [wseemann/FFmpegMediaMetadataRetriever#144]
Obtain the second video thumbnails, memory increases, bitmap are easy to be recycled

 FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
                mmr.setDataSource(path);
                String videoTime = mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ARTIST);

                int seconds = Integer.valueOf(videoTime) / 1000;

                for (int i = 0; i < seconds; i++) {
                    Bitmap bitmap = mmr.getFrameAtTime(i * 1000 * 1000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST_SYNC);

                    if (bitmap != null){

                        bitmapArrayList.add(bitmap);

                    }
                }
                mmr.release();

**Comment by wseemann** [comment]
You are generating a large amount of bitmaps most likely and then storing them in memory. It's pretty logical you would run out of memory at some point if you aren't freeing the resources up.
