### ISSUE TITLE
getFrameAtTime OutOfMemoryError

### ISSUE THREAD

**Issue by jaydonga** [wseemann/FFmpegMediaMetadataRetriever#147]
Retrieving `Bitmap` from video in loop and saving `Bitmap` to `ArrayList` results in `OutOfMemoryError`

```
while (oneSecondInMilli < dur) {
     listFrames.add(mmRetriever.getFrameAtTime(oneSecondInMilli * 1000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST));
     oneSecondInMilli = oneSecondInMilli + 100;
}
```

**Comment by wseemann** [comment]
@jaydonga Yes, you are filling an array with several hundred (if not thousands) of objects that consume memory. This is the expected outcome. If you are trying to capture images I suggest using an approach that doesn't consist of trying to store all of them in memory at once.
