### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by czifraj2** [wseemann/FFmpegMediaMetadataRetriever#148]
Hello, i got this error when i want to build my app. 

Error:Execution failed for task ':metalibrary:buildFFmpeg'.
> A problem occurred starting process 'command 'C:\Users\janok\AndroidStudioProjects\MiRadionk\mlibrary\src\main\ffmpeg\build-ffmpeg.sh''

The file is reachable. Can you help me?

**Comment by wseemann** [comment]
@czifraj2 Please include more information, perhaps a more detailed log of the build you attempted. This snippet alone doesn't provide enough information for me to debug the issue.

**Comment by wseemann** [comment]
Closed due to inactivity.
