### ISSUE TITLE
getFrameAtTime and thread-safety

### ISSUE THREAD

**Issue by storix** [wseemann/FFmpegMediaMetadataRetriever#149]
Hi,

Could you tell me, is it safe to call `getFrameAtTime` from multiple threads?

**Comment by wseemann** [comment]
@storix Yes, they are thread safe, if you look in [mediametadataretriever.cpp](https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/dev/gradle/fmmr-library/library/src/main/jni/metadata/mediametadataretriever.cpp) you'll see references to `Mutex::Autolock _l(mLock)`. This mutex prevents concurrent calls to certain methods, including `getFrameAtTime`.
