### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Gao-Jie** [wseemann/FFmpegMediaMetadataRetriever#150]
Information:Gradle tasks [:fmmr-demo:assembleDebug]
Information:0 errors
Information:0 warnings
Information:See complete output in console
Error:Execution failed for task ':library:buildFFmpeg'.
> Process 'command '/Users/xxx/Desktop/androidplayer/FFmpegMediaMetadataRetriever-master/gradle/fmmr-library/library/src/main/ffmpeg/build-ffmpeg.sh'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 1.584 secs

**Comment by wseemann** [comment]
@Gao-Jie Please include more information, perhaps a more detailed log of the build you attempted. This snippet alone doesn't provide enough information for me to debug the issue.
