### ISSUE TITLE
Gradle error.

### ISSUE THREAD

**Issue by JavaBoyHW** [wseemann/FFmpegMediaMetadataRetriever#152]
I use your library. My Project build.gradle is this :
`buildscript {
    repositories {
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.14'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`
My Module build.gradle is this :
`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.0'
    testCompile 'junit:junit:4.12'

    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-armeabi:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-armeabi-v7a:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-x86:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-mips:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-x86_64:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-arm64-v8a:1.0.14'
}
`
When I sync, the android studio give me error :
"Could not find method compile() for arguments[com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.14] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler."
How can I solve this problem?

**Comment by wseemann** [comment]
I'm not sure what's going on, but I just created a sample application that uses FFmpegMediaMetadataRetriever yesterday. Compare [my projects](https://github.com/wseemann/FFmpegMediaMetadataRetriever-ListExample) `build.gradle` to yours.

**Comment by power7714** [comment]
What's at the very top of your "app" gradle file?

**Comment by wseemann** [comment]
@power7714, who are you asking, me or @JavaBoyHW?

**Comment by power7714** [comment]
Lol sorry I was asking @JavaBoyHW 
Thank you for answering my email though. I'll try it out.

**Comment by wseemann** [comment]
@power7714, no problem. Your top level `build.gradle` doesn't require anything special to use FFmpegMediaMetadataRetriever.

**Comment by power7714** [comment]
@wseeman true but android studio not finding the method compile() could be a result of the gradle file not declaring android.application at the top. Correct?

**Comment by wseemann** [comment]
@power7714, your top level build file should only contain common configuration options, your module/app level build.properties is where your `android.application` and `compile` declarations should be made. Make sense?
