### ISSUE TITLE
I already have ffmpeg in the project, how do I merge FFmpegMediaMetadataRetriever into one?

### ISSUE THREAD

**Issue by xiandanin** [wseemann/FFmpegMediaMetadataRetriever#153]

**Comment by KnIfER** [comment]
[Merge ijkplayer and FMMR](https://github.com/KnIfER/ijk-metadata-retriever)

**Comment by wseemann** [comment]
FFmpegMediaMetadataRetriever uses a JNI interface and the native binaries are loaded using the package name `wseemann.media`. You would need to modify your project or this one to load the binaries from a specific location and ensure they are compiled with the correct options to support both libraries.
