### ISSUE TITLE
Duplicate entry error at launch

### ISSUE THREAD

**Issue by karthikveeramani** [wseemann/FFmpegMediaMetadataRetriever#157]
After building the code that uses this API, I tried running the app on an emulator and got this error:

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: wseemann/media/FFmpegMediaMetadataRetriever$Metadata.class

I'm guessing I need to do something in build.gradle to fix this. Any clue what that is? I made an attempt similar to this thread:

https://stackoverflow.com/questions/37272750/error-during-building-an-apk-file-in-android-studio-2-1-1

to add "packagingOptions" but that did not help.

**Comment by AlohaLorraine** [comment]
hello, I'm having this problem too, have you solved it ?

**Comment by wseemann** [comment]
I separated the core interface from the native binaries. This duplicate error doesn't appear to be an issue as of version [1.0.16](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.16).
