### ISSUE TITLE
setDataSource failed: status = 0xFFFFFFFF

### ISSUE THREAD

**Issue by faizrehman1** [wseemann/FFmpegMediaMetadataRetriever#158]
static FFmpegMediaMetadataRetriever  mmr =new FFmpegMediaMetadataRetriever();
  mmr.setDataSource(link); // error occurs with https link .. but work fine with http :/

**Comment by lyl15151865258** [comment]
The same error.

**Comment by wseemann** [comment]
https is officially supported as of version [1.0.16](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.16).
