### ISSUE TITLE
TimedMetadata for Android

### ISSUE THREAD

**Issue by raihanabbas232** [wseemann/FFmpegMediaMetadataRetriever#159]
@wseemann I have tested and integrated this library and I have successfully extracted metadata like Album-Name, Artist Name Bitrate and so on. But I am given a task where I have to extract some metadata that is injected into a Live Stream.
Do you have any Idea how to retrieve "Timed" Metadata from HLS?
I have implemented Android Provided listener `mMediaPlayer.setOnTimedMetaDataAvailableListener(this);` but its not working?
Seeking your kind consideration

**Comment by wseemann** [comment]
The easiest way to accomplish this with FFmpegMediaMetadataRetriever would be to poll the audio url on a timed interval and check to see if the metadata changed.
