### ISSUE TITLE
error while building my project with this dependency 

### ISSUE THREAD

**Issue by Project-Lib** [wseemann/FFmpegMediaMetadataRetriever#167]
Error:Could not find FFmpegMediaMetadataRetriever.aar (com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.14).
Searched in the following locations:
    https://jcenter.bintray.com/com/github/wseemann/FFmpegMediaMetadataRetriever/1.0.14/FFmpegMediaMetadataRetriever-1.0.14.aar

**Comment by wseemann** [comment]
Please use `mavenCentral()` in your projects `build.gradle`.
