### ISSUE TITLE
no static or non-static method _setDataSource

### ISSUE THREAD

**Issue by Yuuuuun** [wseemann/FFmpegMediaMetadataRetriever#168]
ERROR: FFmpegMediaMetadataRetriever native registration failed
art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lwseemann/media/FFmpegMediaMetadataRetriever;._setDataSource(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V"

why occured this error when I added all .so file to project's "libs' in android studio?

**Comment by dahis39** [comment]
I'm having this crash too. It's caused by ProGuard. When I disable ProGuard in my release build it runs fine. I tried putting -keep class wseemann.media.FFmpegMediaMetadataRetriever.** { *; } into ProGuard config, but this error remains.

**Comment by dahis39** [comment]
I solved it by excluding both the class in your app that use FFmpegMediaMetadataRetriever and the whole FFmpegMediaMetadataRetriever library in your ProGuard config.

My scripts:
-keep class com.xxx.app.package.class { *; }
-keep class wseemann.media.FFmpegMediaMetadataRetriever { *; }

**Comment by AlohaLorraine** [comment]
@dahis39 Thanks very much! it works!

**Comment by wseemann** [comment]
Thanks for the help @dahis39!
