### ISSUE TITLE
app:transformNativeLibsWithMergeJniLibsForDebug

### ISSUE THREAD

**Issue by har2008preet** [wseemann/FFmpegMediaMetadataRetriever#175]
Getting error on including dependencies 
dependencies {
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-armeabi:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-armeabi-v7a:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-x86:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-mips:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-x86_64:1.0.14'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever-arm64-v8a:1.0.14'
}

**Comment by wseemann** [comment]
Closed due to lack of information. Without relevant code or error logs I cannot debug or reproduce your issue.
