### ISSUE TITLE
Getting a frame near the duration of the video returns null

### ISSUE THREAD

**Issue by mebibou** [wseemann/FFmpegMediaMetadataRetriever#176]
When using this code:
```java
FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
mmr.setDataSource(videoFile);
Long duration = Long.parseLong(mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION));
Bitmap bitmap = mmr.getFrameAtTime(duration, FFmpegMediaMetadataRetriever.OPTION_CLOSEST);
```
I get a `null` bitmap. I've tried to remove a bit of buffer on the duration, and on my 5 seconds video I can only get a frame up to 4.5 seconds.
2 questions:
- is there a particular reason?
- would it be possible to just return the closest possible frame instead of returning null?

**Comment by HBiSoft** [comment]
Did you find a solution?

**Comment by mebibou** [comment]
No, i have to remove .5s on the duration to make sure I get something
