### ISSUE TITLE
Prebuilt aar with https

### ISSUE THREAD

**Issue by marinalexandru** [wseemann/FFmpegMediaMetadataRetriever#177]
I used the provided https aars provided in the README.md in the build file in this way:

   - copied them in libs folder

   - added flatDir in app level build.gradle
   repositories {
        jcenter()
        google()
        flatDir {
            dirs 'libs'
        }
    }

  - added the dependency in module level build.gradle
  compile(name:'all-fmmr', ext:'aar')

The project builds but at the following line 
mFFmpegMediaMetadataRetriever.setDataSource(videoUrl);
Im getting  java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF for this setup (it works with http fine just with https doesnt work) 

I also tried to  use the aar for my phones architecture the https one:
compile(name:'arm_64-fmmr', ext:'aar')

I tried to build the aars myself but im on the windows machine and the build on windows is not supported. so i wonder maybe that the aars are not rebuilt in the last commit (or with the latest https modifications) so maybe someone else can built them. 

Thanks in advance

**Comment by pabloserranof** [comment]
Same issue for me

**Comment by irehleecka28** [comment]
i have the same issue, anyone found a workaround for this?

**Comment by Easy-Ez** [comment]
@irehleecka28  me too, have you fixed it?

**Comment by wseemann** [comment]
Closing this issue, https is officially supported in the [latest version](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.16). The prebuilt .so files are deprecated and should not be used.
