### ISSUE TITLE
setDataResource() failed.

### ISSUE THREAD

**Issue by Prateek1105** [wseemann/FFmpegMediaMetadataRetriever#178]
I am getting error : java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
 on code : 

@Override
    public View getView(int i, View view, ViewGroup viewGroup) {

        view = inflater.inflate(R.layout.customlayout , null);
        tv = (TextView)view.findViewById(R.id.textView2);
        iv = (ImageView)view.findViewById(R.id.imageView);
        tv.setText((String) songs.get(i));

        metaRetriver.setDataSource((String) path.get(i));
        try {
            art = metaRetriver.getEmbeddedPicture();
            Bitmap songImage = BitmapFactory.decodeByteArray(art, 0, art.length);
            iv.setImageBitmap(songImage);
        }

        catch (Exception e) {
            //iv.setBackgroundColor(Color.GRAY);
        }

        return view;
    }

**Comment by zeeshanaslam78** [comment]
Try this 

```Java
FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
mmr.setDataSource((String) path.get(i));  

Bitmap bm = mmr.getFrameAtTime(2000000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST);

iv.setImageBitmap(bm);

mmr.release();

**Comment by wseemann** [comment]
@Prateek1105 The exception is self explanatory. It means the data source you passed is invalid. Perhaps it has contains an unsupported protocol, the path is incorrect, etc.
