### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by mbmc** [wseemann/FFmpegMediaMetadataRetriever#18]
Hi,

for people using Android Studio and gradle, the .so should be under <module>/src/main/jniLibs/armeabi/. If you put them somewhere else, you'll get an UnsatisfiedLinkError exception.

**Comment by lessthanoptimal** [comment]
Might want to update the readme to clarify where the files should go in Android Studio.

app/libs = fmmr.jar
app/src/main/jniLibs = armeabi , armeabi-v7a, and the others

**Comment by wseemann** [comment]
Did you know you can fork projects on github and then send a pull request with the requested changes? This means you could have updated the README yourself and contributed to the project rather than waiting for me to do it.
