### ISSUE TITLE
The method "extractMetadata" does not work for "METADATA_KEY_COMMENT"

### ISSUE THREAD

**Issue by subruch** [wseemann/FFmpegMediaMetadataRetriever#193]
The method "extractMetadata" does not work for "METADATA_KEY_COMMENT".

If the mp3 file has an picture then the picture type is returned -> "Cover (front)"
A null is returned if there is no image in the meta data.

**Comment by wseemann** [comment]
I don't understand your issue. Calling `extractMetadata` with `METADATA_KEY_COMMENT` is supposed to return "The metadata key to retrieve the any additional description of the file" (per the documentation). This has nothing to do with images or album art at all.

**Comment by wseemann** [comment]
Closed due to inactivity.
