### ISSUE TITLE
A very short video can't get the last frame, like a video with only 1 second?

### ISSUE THREAD

**Issue by RockyQu** [wseemann/FFmpegMediaMetadataRetriever#195]
Is there something I have written wrong?
this my code:

private Bitmap GetFramePictures(String url) {
        FFmpegMediaMetadataRetriever mediaMetadataRetriever = new FFmpegMediaMetadataRetriever();

        mediaMetadataRetriever.setDataSource(url);
        FFmpegMediaMetadataRetriever.Metadata metadata = mediaMetadataRetriever.getMetadata();
        Logg.e( metadata.getLong("duration"));
//        Bitmap videoShortCut = mediaMetadataRetriever.getFrameAtTime( );
        long ffmduration = Long.parseLong(mediaMetadataRetriever.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION));
        Logg.e( ffmduration);
        Bitmap bitmap1 = mediaMetadataRetriever.getFrameAtTime(ffmduration * 1000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST);
        mediaMetadataRetriever.release();
        return bitmap1;
    }

**Comment by quancs** [comment]
I have meet the same bug. I cannot get the last frame of the video.

**Comment by andreififiita** [comment]
Same here. Any updates?
