### ISSUE TITLE
Duplicate jar entry [wseemann/media/FFmpegMediaMetadataRetriever.class]))

### ISSUE THREAD

**Issue by rubysuki** [wseemann/FFmpegMediaMetadataRetriever#197]
Firstly, thanks for your source.
When i add support individual ABIs: 

dependencies { 
  implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-armeabi-v7a:1.0.14'
  implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-arm64-v8a:1.0.14'
}

Then i build release source, but Android Studio always show error : 
(Can't read [...\caches\transforms-1\files-1.1\FFmpegMediaMetadataRetriever-arm64-v8a-1.0.14.aar\ab078182cdda2c8c2a4efe58cadd584a\jars\classes.jar(;;;;;;;**.class)] (Duplicate jar entry [wseemann/media/FFmpegMediaMetadataRetriever.class]))
I use multidexEnalbe : true but can't build release source.
Please help me, thank you so much !

**Comment by Purvik** [comment]
Have you found any solution for this one @rubysuki  ?

**Comment by rubysuki** [comment]
yes, @Purvik 
I downloaded aar file, then I removed some folders that I don't need on this file. I kept two folder : armeabi-v7a and arm64-v8a. 
After that, I import aar file into my project.
