### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by Carlos2927** [wseemann/FFmpegMediaMetadataRetriever#201]
Can you publish a new release?  The lastest release v1.0.14 is released on 1 Dec 2016! If you fixed some bugs, you should release it as soon as possible.

**Comment by wseemann** [comment]
When I have something that I feel is worth publishing then I will publish a new release. If I published a new release every time I fixed a few small bugs this project would require a great deal time. This is the reason I make the source code available. If you want a bleeding edge release feel free to fork the repo and build your own version.

**Comment by HBiSoft** [comment]
@wseemann 

> If I published a new release every time I fixed a few small bugs this project would require a great deal time.

In more than 2 year and 38 issues (where the first was posted 5 April 2015), there must of been a hand full of bug that was worth fixing?
