### ISSUE TITLE
This library 64-bit compliant ?

### ISSUE THREAD

**Issue by vasim0234** [wseemann/FFmpegMediaMetadataRetriever#207]
Hello,
Thanks for your making great library

As we are using your library,but recently we got email from play store that make app as compitable with 64 bit compilant so this library is 64 bit compliant if not what we have to do can you suggest on that 

We are using this way

    armeabiImplementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-armeabi:1.0.14'
    armeabi_v7aImplementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-armeabi- v7a:1.0.14'
    x86Implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-x86:1.0.14'
    x86_64Implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-x86_64:1.0.14'
    arm64_v8aImplementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-arm64-v8a:1.0.14'

We would like to you please give solution for same

**Comment by HBiSoft** [comment]
You can have a look at an answer I ask some time ago, it might help you - https://stackoverflow.com/q/52253127/8199772

**Comment by wseemann** [comment]
Thanks for the input @HBiSoft! @vasim0234 this library supports arm64-v8a and x86_64. I suspect the email you received is related to how you are bundling your actual app. You should be creating separate APKs for each ABI.
