### ISSUE TITLE
Application Size is Increased by 23-24 mb

### ISSUE THREAD

**Issue by developersTeem** [wseemann/FFmpegMediaMetadataRetriever#208]
I found this library very useful for me before this i am using MediaMetaDataRetriever  mmr ; which gives me error on mmr.setDataSource(); So i am trying to use this and also it solved my problem but the size of application after implementation of this lib is increased by 23 mb before this my application size is only 4 mb now it is 29 mb. 

I found some answers in changing build.gradle

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "app_id"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 6
        versionName "3.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        splits {
            abi {
                enable true
                reset()
                include 'x86', 'armeabi-v7a', 'x86_64'
                universalApk true
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

But i don't know how it will solve my problem because still my universal apk size is 29 mb

Thanks

**Comment by wseemann** [comment]
In order to reduce application size I recommend creating build-variants for each supported architecture and then using only the corresponding variant of this library for each APK.

More info can be found here: https://developer.android.com/studio/build/build-variants
