### ISSUE TITLE
Major Brand is not returning the correct result

### ISSUE THREAD

**Issue by linda-dge** [wseemann/FFmpegMediaMetadataRetriever#211]
I have the following code:

FFmpegMediaMetadataRetriever retriever = new FFmpegMediaMetadataRetriever();
retriever.SetDataSource(path);
retriever.ExtractMetadata("major_brand");

It is returning _MSNV_ when I can see in the Exiftool it should be returning _MPEG-4 (.MP4) for SonyPSP_

This is the result from both an online exif tool and exiftool

Major Brand                     : MPEG-4 (.MP4) for SonyPSP
Minor Version                   : 15a.0.70
Compatible Brands               : MSNV, mp42, isom

Do you have any idea how I could get that value?

**Comment by wseemann** [comment]
Hi Linda, I would check the file using `ffmpeg -i "path the file"` and see what the metadata output is. Do you have a file I can test against? `major_brand` is not currently supported by this library, which could be part of the problem.

**Comment by linda-dge** [comment]
You are right!

ffmpeg doesn't get major brand either.  I wonder where exif tool gets the
word "Sony" from.  Argh.  So frustrating.  I wish camera manufacturers
would stamp their video with something that indicates who they are.

Here is the file  none the less.

Thank you for all that you do.  I appreciate it.
 MAH00606.MP4
<https://drive.google.com/a/dynagrace.com/file/d/14O299HAi7W8eNdmFjefTc7On1hUHOXuk/view?usp=drive_web>

*Linda Rawson*


ᐧ

**Comment by wseemann** [comment]
@linda-dge here is the output from ffmpeg. Would having `major_brand` returned help?
![Screen Shot 2019-08-20 at 10 23 12 AM](https://user-images.githubusercontent.com/2296196/63369441-cc036100-c334-11e9-9ad3-c90398f25a2f.png)

**Comment by linda-dge** [comment]
No.  I forgot to mention I tried it as well.

The attached is what exiftool shows for majorbrand

exiftool -majorbrand MAH00606.MP4

[image: image.png]

*Linda Rawson*


ᐧ
