### ISSUE TITLE
Unable to get network video stream specified frame

### ISSUE THREAD

**Issue by HaiGao** [wseemann/FFmpegMediaMetadataRetriever#213]
Who Can Help Me？？？
Two things:
ONE:
My code is probably like this：
String url = "A video stream URL"；

Bitmap bitmap= null;

FFmpegMediaMetadataRetriever retriever = new FFmpegMediaMetadataRetriever();

retriever.setDataSource(url,new HashMap<String, String>());

//Bitmap=retriever.getFrameAtTime();//It's ok
Bitmap=retriever.getFrameAtTime(1000,FFmpegMediaMetadataRetriever.OPTION_CLOSEST);//It's has problem...

TWO:
And I found that FFmpegMediaMetadataRetriever can't read RTSP stream, is that true?

**Comment by HBiSoft** [comment]
It makes sense that the following is not working:

```java
Bitmap=retriever.getFrameAtTime(1000,FFmpegMediaMetadataRetriever.OPTION_CLOSEST);
```

If you call the above inside `onCreate`, for example, then the stream has not yet buffered the frame you are looking and it will not be available. You can test this by delaying the above with 2-3 seconds..

**Comment by wseemann** [comment]
Version [1.0.16](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.16) was just released and now fully supports RTSP. Please update to this version and let me know if you encounter any issues. Thanks!
