### ISSUE TITLE
Adding function about multi stream file

### ISSUE THREAD

**Issue by whitecloudy** [wseemann/FFmpegMediaMetadataRetriever#215]
The current code only handles the first stream of video and audio. But, some media files(like a video created from car black box) which have more than two streams need some options which stream will be used.

I just briefly read some source code of "ffmpeg_mediametadataretriever.c" and it seems that this option can be added pretty easily(not sure though).

**Comment by wseemann** [comment]
Good suggestion. Can you provide a sample video for me to test with?

**Comment by wseemann** [comment]
Closed due to inactivity.
