### ISSUE TITLE
Question: Can this library be used in commercial project

### ISSUE THREAD

**Issue by methelas** [wseemann/FFmpegMediaMetadataRetriever#216]
Hey 👋 
I was reading about the `FFMPEG` license and all, but couldn't find any definitive answer.

Can this library be used in a closed-source commercial app?
If so what steps should I take to make sure noone will come after me for using it?

**Comment by HBiSoft** [comment]
FFmpeg is licensed under[ LGPLv2.1](http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html), but you have not modified any FFmpeg source code, you are using a library(FFmpegMediaMetadataRetriever) that uses FFmpeg. It is the responsibility of this library to meet all the LGPLv2.1 licensing agreements.

**BUT-**
FFmpegMediaMetadataRetriever is licensed under Apache License Version 2.0, [here](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) is a quick overview of the Apache terms.

So if you have made any changes to this library, then you will need to state the changes, include the copyright and license.

If you are just using the library without changing any of its source code, then you are good to go.

**Comment by wseemann** [comment]
Disclaimer: I am not a lawyer so my response should not be taken as professional legal advice. Use of FFmpeg in a project may require the project itself to be licensed under the LGPLv2.1 depending on both the flags used to compile FFmpeg in addition to the way it is linked (static versus dynamic).
