### ISSUE TITLE
Build failed for armeabi-v7a

### ISSUE THREAD

**Issue by jackflyer** [wseemann/FFmpegMediaMetadataRetriever#220]
Build failed for armeabi-v7a using ndk 19 /(also tried ndk 15) with following error.

binary/src/main/jni/metadata/wseemann_media_MediaMetadataRetriever.cpp:146:11: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
    char *restrict_to = strstr(tmp, "mms://");
          ^             ~~~~~~~~~~~~~~~~~~~~~

Note : Build success for x86_64 and other.

**Comment by wseemann** [comment]
This fixed in [this](https://github.com/wseemann/FFmpegMediaMetadataRetriever/commit/ca4739036db56c26a448f62556ff9b595a19311d) commit. The fix will be included in the next release. If you do a fresh pull from master compilation should work using ndk r20.
