### ISSUE TITLE
JNI_ERR returned from JNI_OnLoad

### ISSUE THREAD

**Issue by VikasGutte** [wseemann/FFmpegMediaMetadataRetriever#221]
getting following error - 

`JNI_ERR returned from JNI_OnLoad in "/data/app/com.xxx.Mp3xxx-Rmn6lrV5xU0punPwmdtk9g==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libffmpeg_mediametadataretriever_jni.so"`

` at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(FFmpegMediaMetadataRetriever.java:24)`

**Note :- tried all provided ans but not working for android Version: 9**

**Comment by wseemann** [comment]
The `minSdkVersion` of this library is API 14. Your OS isn't supported.
