### ISSUE TITLE
Getting Album art using FFmpegMediaMetadataRetriever and Exoplayer

### ISSUE THREAD

**Issue by Tucker2015** [wseemann/FFmpegMediaMetadataRetriever#227]
Is it possible to get album art using FFmpegMediaMetadataRetriever and Exoplayer ?

Im using a simple  player to stream from a Shoutcast source.  I can retrieve the metadata and show the title and track but would like to add album art if possible.

Thanks

**Comment by wseemann** [comment]
Yes, you can use [getEmbeddedPicture()](http://wseemann.github.io/FFmpegMediaMetadataRetriever/apidocs/wseemann/media/FFmpegMediaMetadataRetriever.html#getEmbeddedPicture()) or [getFrameAtTime()](https://wseemann.github.io/FFmpegMediaMetadataRetriever/apidocs/wseemann/media/FFmpegMediaMetadataRetriever.html#getFrameAtTime()) to retrieve the album art, if it exists.

**Comment by annhienktuit** [comment]
> Yes, you can use [getEmbeddedPicture()](http://wseemann.github.io/FFmpegMediaMetadataRetriever/apidocs/wseemann/media/FFmpegMediaMetadataRetriever.html#getEmbeddedPicture()) or [getFrameAtTime()](https://wseemann.github.io/FFmpegMediaMetadataRetriever/apidocs/wseemann/media/FFmpegMediaMetadataRetriever.html#getFrameAtTime()) to retrieve the album art, if it exists.

It quite slow to get a list of EmbeddedPictures, do you have any solution to speed this up? @wseemann

**Comment by lucario852** [comment]
> Sí, puede usar [getEmbeddedPicture()](http://wseemann.github.io/FFmpegMediaMetadataRetriever/apidocs/wseemann/media/FFmpegMediaMetadataRetriever.html#getEmbeddedPicture()) o [getFrameAtTime()](https://wseemann.github.io/FFmpegMediaMetadataRetriever/apidocs/wseemann/media/FFmpegMediaMetadataRetriever.html#getFrameAtTime()) para recuperar la carátula del álbum, si existe.


Could you show me how is the method or the structure of the code to obtain the image of the album?
