### ISSUE TITLE
Block UI

### ISSUE THREAD

**Issue by AdilSattar1233** [wseemann/FFmpegMediaMetadataRetriever#229]
I am using it in recyclerview. When i load data its block my UI and for scrolling up data.

**Comment by wseemann** [comment]
How are you using the library in your recycler view? Without some sort of code snippet I'm unable to help with your issue.

**Comment by AdilSattar1233** [comment]
I am using it in recyclerview. I am getting video from firebase and then using your library it fetching but block my UI

**Comment by wseemann** [comment]
I asked for a code snippet. I cannot debug your issue without one, therefore I'm closing this issue.
