### ISSUE TITLE
possible native memmory leak

### ISSUE THREAD

**Issue by shay-rom** [wseemann/FFmpegMediaMetadataRetriever#23]
i noticed i have a native memmory related crash while using the library.
each call to setDataSource & getFrameAtTime allocates several MB from the native heap.
calling release() does not free it.

i use this code to check the memory related crash:
		for(int i=0 ; i<60 ; i++){
			Log.d("","iteration "+i);
			printNativeMemoryHeapAllocationSize();
			fmmr = new FFmpegMediaMetadataRetriever();
			printNativeMemoryHeapAllocationSize();
			
			String pathToFile = "/mnt/sdcard/movie.mp4";
			fmmr.setDataSource(pathToFile);
			printNativeMemoryHeapAllocationSize();
			Bitmap bmp = fmmr.getFrameAtTime(1000);
			printNativeMemoryHeapAllocationSize();		
			fmmr.release();
			bmp.recycle();
			System.gc();
			printNativeMemoryHeapAllocationSize();			
		}

	private void printNativeMemoryHeapAllocationSize(){
		Log.d("memory test","native heap alloc size: "+Debug.getNativeHeapAllocatedSize());
	}

am i doing something wrong?

**Comment by danielmoraes** [comment]
I noticed this same issue on the most recent version of the library.

**Comment by MohHeader** [comment]
me too :(

**Comment by denite** [comment]
Ditto... Any way to get around this?

**Comment by Filimindji** [comment]
Hi,

Same issue here.

Is there any fix about that ?

Thank you,

**Comment by Filimindji** [comment]
Hi,

I have done some research about that. It look like that the native JNI library should be unloaded when the classloader which loaded the library is garbage collected. (according to http://stackoverflow.com/questions/453359/how-to-unload-library-dll-from-java-jvm)

I was hopping that this operation can "resolve" the memory leak. But it don't.

I did a really simple app that do that in a loop : 

FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
mmr.setDataSource(desc);
mmr.release();

After ~220 iteration, the app crash.

**Comment by wseemann** [comment]
I've looked into this issue and I'm not sure there is a way around it. Android loads FFmpeg each time you create a new instance of `FFmpegMediaMetadataRetriever` and calling `release()` doesn't seem to unload the references. I've spent a fair amount of time looking into this issue and I haven't found a solution. As a workaround, it's not necessary to create a new instance of `FFmpegMediaMetadataRetriever` each time you call `setDataSource`. Perhaps you should try reusing the same `FFmpegMediaMetadataRetriever` instance until you have extracted metadata from all the files and then call `release()` only once.

**Comment by Filimindji** [comment]
Thank you for the feedback.

I think You are right. As a workaround I dont execute my code in a loop, by less frequently after a specific user action.

Now the garbage collector have more opportunity to really release the memory, and my app do not crash anymore.

I think your advise to create only one instance of  FFmpegMediaMetadataRetriever is good too. But in my case, the code is placed into an android plugin called by a C# method into an unity project (my interop skills just reach a new level :)

**Comment by wseemann** [comment]
Fixed in the latest release, version 1.0.11.

**Comment by tonggang2013** [comment]
This issue still is exist at version 1.0.11!

**Comment by zjupure** [comment]
still memory leak in native
