### ISSUE TITLE
Github host mp3 and setDataSource failed: status = 0xFFFFFFFF

### ISSUE THREAD

**Issue by Thanhtho96** [wseemann/FFmpegMediaMetadataRetriever#230]
I have some mp3, flac host on Github repo and I setDataSource with MediaPlayer is super fine, everything running smoothly with RAW type (I add to header ["Accept"] = "application/vnd.github.v3.raw") `mediaPlayer.setDataSource(context, Uri, headerMap)`

But with FFmpegMediaMetadataRetriever I get 0xFFFFFFFF when setting the same data source
`mmr.setDataSource(Uri, headerMap)`

Does anyone has tried with Github mp3 source? Here is my music repo if you wanna test [https://github.com/Thanhtho96/music](url)

**Comment by flykule** [comment]
I dont think this repo support raw type nor in ffmpeg. I suggest you use MediaMetaDataRetriever instead.

**Comment by Thanhtho96** [comment]
> I dont think this repo support raw type nor in ffmpeg. I suggest you use MediaMetaDataRetriever instead.

Got it, do you know how to go async with it because its block in main thread. I know can go with coroutine but I want to know if there are API for it. like prepareAsync
