### ISSUE TITLE
FFmpegMediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH crash

### ISSUE THREAD

**Issue by jllarraz** [wseemann/FFmpegMediaMetadataRetriever#232]
When I try to recover the resolution of a video the app crash. 

FFmpegMediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH

**Comment by ArtanBerisha1** [comment]
Show more info, e.g:
What error is showing when your app crashes ?
When and how are you calling this (this constant that you typed should be added as parameter to extractMetaData() method)?

**Comment by wseemann** [comment]
Closed due to lack of information. I cannot reproduce an issue without relevant code samples.
