### ISSUE TITLE
Does it support RTSP?

### ISSUE THREAD

**Issue by Paranormaly** [wseemann/FFmpegMediaMetadataRetriever#237]
I'm trying to get frame from rtsp link but no luck.
I used the same code on local android video things are going well.
I'm using a simple very simple code 

        mFFmpegMediaMetadataRetriever = new FFmpegMediaMetadataRetriever();
        //mFFmpegMediaMetadataRetriever.setDataSource("/storage/emulated/0/Download/videoplayback.mp4");
        mFFmpegMediaMetadataRetriever.setDataSource("rtsp://ip:port");

        Bitmap frame = mFFmpegMediaMetadataRetriever.getFrameAtTime();
        Log.i("FF","Frame:: "+frame);
`
the frame is always null
I read many isuues here about rtsp but no one said  it worked for him
Is there any trick for rtsp?

**Comment by wseemann** [comment]
Hello @Paranormaly, RTSP is confirmed to be working correctly as of version [1.0.16](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.16). I tested with this link: `rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4`. Please update to this version and let me know if you encounter any issues. Thanks!
