### ISSUE TITLE
getScaledFrameAtTime  more and more slow

### ISSUE THREAD

**Issue by codeingLiu** [wseemann/FFmpegMediaMetadataRetriever#242]
I use getScaledFrameAtTime  more and more slow  ,How to solve?  thanks！
I can get 12 frames per second at the beginning, and only one stitch per second at the end

**Comment by wseemann** [comment]
I'd need to see exactly how you are using the library to debug your issue. Are you doing this in a loop, do you create a new FFmpegMediaMetadataRetriever instance on each pass, do you release the old instance, etc.

**Comment by wseemann** [comment]
Closed due to inactivity.
