### ISSUE TITLE
Metadata could not be retrieved

### ISSUE THREAD

**Issue by target1314** [wseemann/FFmpegMediaMetadataRetriever#244]
![image](https://user-images.githubusercontent.com/16127526/118782457-b2ec6300-b8c0-11eb-8ee4-09baf0fddd3f.png)

Metadata could not be retrieved

**Comment by wseemann** [comment]
Version [1.0.16](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.16) was just released and now fully supports https. Please update to this version and let me know if you encounter any issues. Thanks!
