### ISSUE TITLE
about FFmpeg  version?

### ISSUE THREAD

**Issue by dufangyu1990** [wseemann/FFmpegMediaMetadataRetriever#247]
the 1.0.5 version depends on FFmpeg 4.2.2?  if not,are there any plans to upgrade FFmpeg  version ?

**Comment by wseemann** [comment]
At some point I will definitely update to a newer FFmpeg version. It's a very time consuming process though, so it may be another couple of months before that change goes in. Is there a specific feature or reason you'd like a newer version of FFmpeg included with the library?

**Comment by wseemann** [comment]
The [latest release](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.16) is now using FFmpeg 4.4.1. You should update the version of the library you are using since older binaries are unsupported and won't be updated.
