### ISSUE TITLE
cannot get video bitrate and https is not supported

### ISSUE THREAD

**Issue by DeVictorVH** [wseemann/FFmpegMediaMetadataRetriever#248]
File urls with https protocol do not work even using the prebuilt arrs and the bitrate of videos cannot be obtained.
Has the last update been released more than a year ago, do you plan to support these problems?

**Comment by DeVictorVH** [comment]
Thanks for your answer, I installed the test apk and it does not seem to work, I tried with the default url and another one but it did not work (I tried it on a Xiaomi Redmi 9 with android 10). What will be the problem?

**Comment by wseemann** [comment]
Can you post the URL you are trying to test?

**Comment by DeVictorVH** [comment]
> Can you post the URL you are trying to test? Xiaomi Redmi 9 might be the issue. Does the test APK crash or simply not return any result? I tested with the default URL and I know that works so your issue might be related to Xiaomi since it runs a modified Android ROM.

It does not return the result, the Toast "Metadata not could be retrieved" appears. 
This is the url of the video I tested: https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4

**Comment by wseemann** [comment]
An unlocked bootloader shouldn't affect anything. I just tried the sample app with the URL you specified and it worked fine on an ARM device (which the Xiaomi Redmi 9 appears to be). So the issue appears to be with the OS itself. I won't be able to help you there since I don't have a Xiaomi OS to test on and they don't make images available.

**Comment by DeVictorVH** [comment]
> An unlocked bootloader shouldn't affect anything. I just tried the sample app with the URL you specified and it worked fine on an ARM device (which the Xiaomi Redmi 9 appears to be). So the issue appears to be with the OS itself. I won't be able to help you there since I don't have a Xiaomi OS to test on and they don't make images available.

I tried it in an emulator and if it worked. If you want to send something to test and fix the error, I will be happy to help you.
