### ISSUE TITLE
does this support armabi？

### ISSUE THREAD

**Issue by denghanhao** [wseemann/FFmpegMediaMetadataRetriever#252]
I get an error when I run it on an armabi device.

java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libavutil.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"

**Comment by wseemann** [comment]
This library currently supports armeabi-v7a, x86, x86_64 and arm64-v8a. As the README states: ARM and MIPS aren't supported as of version 1.0.14
