### ISSUE TITLE
METADATA_KEY_DURATION returns 0 for mpg file.

### ISSUE THREAD

**Issue by pgpathan22** [wseemann/FFmpegMediaMetadataRetriever#255]
```
val retriever = FFmpegMediaMetadataRetriever()
retriever.setDataSource(App.instance, `"path_to_mpg_file"`)
val durationMillis = retriever
            .extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION)
```
[sample_1920x1080.zip](https://github.com/wseemann/FFmpegMediaMetadataRetriever/files/8762408/sample_1920x1080.zip)

I have tried with other file extensions ("mp4", "avi", "mkv", "mov", "wmv", "flv", "webm", "ts") it works well but for this mpg format, it return 0. PFA, it is the video file which is causing issue.

**Comment by wseemannroku** [comment]
This library uses FFmpeg to retrieve the duration. I checked the file you attached and it doesn't not appear to contain the duration. Try adding this metadata to the file and you should see it returned by FFmpegMediaMetadataRetriever.

<img width="1055" alt="Screen Shot 2022-05-24 at 4 53 15 PM" src="https://user-images.githubusercontent.com/103459183/170138547-bb82ab71-ab15-45d0-9023-3d45774bfff2.png">

**Comment by pgpathan22** [comment]
Thanks.
