### ISSUE TITLE
Can’t compile because MediaDataSource.cpp files missing 

### ISSUE THREAD

**Issue by leephela** [wseemann/FFmpegMediaMetadataRetriever#257]
Hello,
The files `wseemann_media_MediaDataSource.cpp ` and `wseemann_media_MediaDataSource.h` seems to be missing from the source. Because of it, the compile always fails, and those mentioned files are nowhere to be found elsewhere in the repo too. 

The Android.mk listed `wseemann_media_MediaDataSource.cpp ` as one of the source files needed for compilation but this file is nowhere to be found and so is `wseemann_media_MediaDataSource.h` included in the other source files.

How do you manage to successfully compile without those missing source files?
Thank you

**Comment by wseemann** [comment]
Hello @leephela, I just added the files in [this commit](https://github.com/wseemann/FFmpegMediaMetadataRetriever/commit/8da4fbaecdd041ac46a0fe56fc99782b7b75cba4), please perform a `git pull` and let me know if this resolves your compilation issues. Thanks for reporting this issue!
