### ISSUE TITLE
OpenSSL lower then 1.1.1i

### ISSUE THREAD

**Issue by gepaopaocai** [wseemann/FFmpegMediaMetadataRetriever#262]
pls update ssl .
play store reject my app.
https://support.google.com/faqs/answer/12576638

**Comment by gepaopaocai** [comment]
@wseemann When will it be updated?

**Comment by wseemann** [comment]
@gepaopaocai I just released version 1.0.19. Please try that version and let me know if you have any issues.

**Comment by Muhammad-Mohsen** [comment]
@wseemann , I'm using version 1.0.19 in my app and I'm getting the below warning when I upload a new build (it's _not_ getting rejected, though):

> One or more of your apps is running an outdated version of OpenSSL, which has multiple security vulnerabilities. You should update OpenSSL as soon as possible.

I don't think I'm using any libraries that can cause this issue (gradle file [here](https://github.com/Muhammad-Mohsen/minimalist-music-kotlin/blob/master/app/build.gradle))
