### ISSUE TITLE
Get thumbnail from HLS VOD content

### ISSUE THREAD

**Issue by forfiter9** [wseemann/FFmpegMediaMetadataRetriever#266]
Hi,

it is possible to get using your library the thumbnail for HLS VOD content? I have now splitted content to 3s segments .m4s, .m3u8 playlist, file_init.mp4 I am trying to get a thumbnail for this. 

Br

**Comment by wseemann** [comment]
Can you provide a sample URL for me to test with? Have you tried passing one of the video segments (not the playlist URL) to FFmpegMediaMetadataRetriever and checked the output?

**Comment by wseemann** [comment]
Closed due to inactivity.
