### ISSUE TITLE
Can not use FFmpegMediaMetadataRetriever

### ISSUE THREAD

**Issue by hsy2016052387** [wseemann/FFmpegMediaMetadataRetriever#268]
I had added this code to my build.gradle,but I can't use any class in this lib.
`implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-core:1.0.19'
    implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-native:1.0.19'`

It worked when use
`implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.14'`

**Comment by wseemann** [comment]
@hsy2016052387 What do you mean by "I can't use any class in this lib."? Did the gradle import not work, did your app not compile, is there an error of some sort?

**Comment by hsy2016052387** [comment]
Looks like I can't pull the lib down when I sync project,but it works when I use 
`implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.14`
