### ISSUE TITLE
FFmpegMediaMetadataRetriever does not respect video rotation in getFrameAtTime

### ISSUE THREAD

**Issue by daio** [wseemann/FFmpegMediaMetadataRetriever#273]
Unlike the framework MediaMetadataRetriever, FFmpegMediaMetadataRetriever does not rotate the frame according to video rotation in container's metadata(can be retrieved using METADATA_KEY_VIDEO_ROTATION).

You can create a sample file with rotation in metadata for testing purposes using ffmpeg:
`ffmpeg -i input.mp4 -metadata:s:v rotate=90 -vcodec copy -acodec copy output.mp4`

**Comment by wseemann** [comment]
Thank you for reporting this issue @daio. This has been fixed and will be available in v1.0.20.
