### ISSUE TITLE
getFrameAtTime always returns null 

### ISSUE THREAD

**Issue by w2ji** [wseemann/FFmpegMediaMetadataRetriever#28]
I used the pre-built jar files with Android Gradle system. 
I put the jar file in the libs folder and the armeabi, armeabi-v7a, mips and x86 folder under 
src/main/jnilibs/

So I have a very simple demo application and I'm trying to fetch frames from a video picked from gallery. But getFrameAtTime always returns null regardless of what the time is. I can fetch the metadata (I think the metadata is being rounded to the nearest thousand) Any ideas?

FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
File file = new File(getPath(videoPath));
            FileInputStream inputStream = new FileInputStream(file);
            mmr.setDataSource(inputStream.getFD());
            String time = mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION);
            Bitmap test = mmr.getFrameAtTime(1000000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST_SYNC);

**Comment by jimmyjzemoso** [comment]
Did you find a solution?
