### ISSUE TITLE
Sometimes frames are rotated

### ISSUE THREAD

**Issue by kjlee38** [wseemann/FFmpegMediaMetadataRetriever#31]
When I used this lib, the frames from getFrameAtTime() were rotated sometimes.

**Comment by Sca09** [comment]
It is happening to me as well, but just in videos that are recorded at this moment in portrait mode. Those in landscape or those taken from gallery works properly, but when you are recording the video in the app in portrait, the preview (getFrameAtTime()) is rotated.

**Comment by hardikJoshi123** [comment]
Same issue as @Sca09
