### ISSUE TITLE
JNI WARNING: input is not valid Modified UTF-8: illegal continuation byte get VM aborting: Fatal signal 11

### ISSUE THREAD

**Issue by Prometeo6** [wseemann/FFmpegMediaMetadataRetriever#34]
Hi,

I'm using FFmpegMediaMetadataRetriever to extract metadata from radio FM stream datasource. When my andorid app call extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ICY_METADATA) and receives as output string: string: 'StreamTitle='SIGLA PUBBLICIT� - Jingle di apertura';StreamUrl='';' (where � = A accented) is generated this stack trace: 

I/MediaMetadataRetrieverJNI(7133): release
I/MediaPlayer(7133): Don't send intent. msg.arg1 = 0, msg.arg2 = 0
W/dalvikvm(7133): JNI WARNING: input is not valid Modified UTF-8: illegal continuation byte 0x20
W/dalvikvm(7133):              string: 'StreamTitle='SIGLA PUBBLICIT� - Jingle di apertura';StreamUrl='';'
W/dalvikvm(7133):              in Lwseemann/media/FFmpegMediaMetadataRetriever;.extractMetadata:(Ljava/lang/String;)Ljava/lang/String; (NewStringUTF)
I/dalvikvm(7133): "main" prio=5 tid=1 NATIVE
I/dalvikvm(7133):   | group="main" sCount=0 dsCount=0 obj=0x41c04508 self=0x41be9ef0
I/dalvikvm(7133):   | sysTid=7133 nice=0 sched=0/0 cgrp=apps handle=1074233136
I/dalvikvm(7133):   | schedstat=( 4024719325 2458892748 6318 ) utm=342 stm=59 core=0
I/dalvikvm(7133):   #00  pc 00001260  /system/lib/libcorkscrew.so (unwind_backtrace_thread+27)
I/dalvikvm(7133):   #01  pc 0005f944  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+35)
I/dalvikvm(7133):   #02  pc 000537ec  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+303)
I/dalvikvm(7133):   #03  pc 00053886  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
I/dalvikvm(7133):   #04  pc 00038e42  /system/lib/libdvm.so
I/dalvikvm(7133):   #05  pc 0003a1f4  /system/lib/libdvm.so
I/dalvikvm(7133):   #06  pc 0003c452  /system/lib/libdvm.so
I/dalvikvm(7133):   #07  pc 00002ac0  /data/data/com.rcn101.activity/lib/libffmpeg_mediametadataretriever_jni.so
I/dalvikvm(7133):   #08  pc 0001deb0  /system/lib/libdvm.so (dvmPlatformInvoke+112)
I/dalvikvm(7133):   #09  pc 0004d102  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+393)
I/dalvikvm(7133):   #10  pc 00027324  /system/lib/libdvm.so
I/dalvikvm(7133):   at wseemann.media.FFmpegMediaMetadataRetriever.extractMetadata(Native Method) 

This maybe generates the VM aborting Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 7133, that making my app crash.

How I can fix this issue. I try to put the call of extractMetadata(...) method in a try/catch block. but no exception is raised.

Thank you very much for your help.

**Comment by wseemann** [comment]
Can you send me the URL you are testing with?

**Comment by Prometeo6** [comment]
Hi,

the URL of the stream is: http://onair15.xdevel.com:8866

This is a stream of a radio fm that play music all the day. During the
trasmission there are also some advertisments. When an advertisment is on
air, the metada stream contains the String: 'StreamTitle='SIGLA PUBBLICIT�
- Jingle di apertura';StreamUrl='';'

2015-01-12 16:52 GMT+01:00 William Seemann <notifications@github.com>:
