### ISSUE TITLE
setDataSource crashes if url is https

### ISSUE THREAD

**Issue by davemess** [wseemann/FFmpegMediaMetadataRetriever#36]
I'm trying to extract metadata from a remote video source. Everything's working as long as the url is http, but it crashes if url is https.

**Comment by wseemann** [comment]
What URL are you trying?

**Comment by davemess** [comment]
Here's a sample that : https://dl.dropboxusercontent.com/u/2076201/vids/udozpbflierp7rb8zlpw.mp4. This resulted in: IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF. Though it seems to work in the demo app?

**Comment by wseemann** [comment]
A couple of things:

1.) The URL you provided produces a 404
2.) An IllegalArgumentException isn't the same as a "crash"
3.) Read the app documentation regarding HTTPS support.

**Comment by davemess** [comment]
Link's fixed. I'll check out the documentation-
