### ISSUE TITLE
How to build FFmpegMediaMetadataRetriever and FFmpegMediaPlayer at the together?

### ISSUE THREAD

**Issue by gusdn9** [wseemann/FFmpegMediaMetadataRetriever#37]
How to build FFmpegMediaMetadataRetriever and FFmpegMediaPlayer at the together in one Project?

**Comment by wseemann** [comment]
Replace you existing JNI folder and ffmpeg zip with the ones found here: https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/master/joint-build-scripts.zip then build the library as you normally do.
