### ISSUE TITLE
not getting some metadata

### ISSUE THREAD

**Issue by prashantwosti** [wseemann/FFmpegMediaMetadataRetriever#38]
Hi, I wanted to fetch metadata which gives the current song title.

    FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
                mmr.setDataSource("http://stream.radiozu.ro:8020/");
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ALBUM);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ALBUM_ARTIST);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ICY_METADATA);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_TITLE);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ARTIST);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_AUDIO_CODEC);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DISC);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_FILENAME);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_FRAMERATE);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_GENRE);
                mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_TRACK);

unfortunately, I'm not getting current song tite, listener peak, stream status. Here is my output:
    
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ icy-genre :: CHR
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ icy-name :: Radio ZU Live
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ icy-notice2 :: SHOUTcast Distributed Network Audio Server/win32 v1.9.8<BR>
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ filesize :: -38
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ audio_codec :: aac
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ icy-notice1 :: <BR>This stream requires <a href="http://www.winamp.com/">Winamp</a><BR>
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ duration :: 0
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ icy-br :: 32
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ icy-pub :: 1
    02-02 07:21:39.389  22950-23009/com.codec.radio I/RADIO﹕ icy-url :: http://www.radiozu.ro

Can you please help me out here. I want all the info as its shown here: http://stream.radiozu.ro:8020/

Thanks

**Comment by wseemann** [comment]
Stream title is retrieved using the `METADATA_KEY_ICY_METADATA` key. The other metadata you want (listener peak, etc.) is not delivered via standard Icecast/SHOUTcast metadata.
