### ISSUE TITLE
getFrameAtTime always return null

### ISSUE THREAD

**Issue by SebSob** [wseemann/FFmpegMediaMetadataRetriever#40]
Hello,

I need to grab the last frame of the video in my VideoView, what i am doing is the following:

// get the time
int endTime = vidView.getDuration() * 1000;

//get the last frame
FFmpegMediaMetadataRetriever fmmr = new FFmpegMediaMetadataRetriever();
fmmr .setDataSource(videoSource);
Bitmap bmFrame = fmmr.getFrameAtTime(endTime, FFmpegMediaMetadataRetriever.OPTION_CLOSEST); 
System.out.println("bmFrame: " + bmFrame); // <- NULL
fmmr.release();

videoSource is something like: 
"/storage/sdcard0/folder/folder/video.mp4"

I have extracted the libs and jar from where and i have put it in my libs. 
https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/master/fmmr-library/prebuilt-libs.tar.gz

My /libs folder contains the following 4 folders and the jar:
-armeabi
-armeabi-v7a
-mips
-x86
fmmr.jar

(= is it btw necassary to have all 4 folders? Because this makes my .apk like 30mb+ ...)

Is this still a bug or am i doing something wrong?
Thanks

**Comment by wseemann** [comment]
1.) It's not necessary to include all folders, you only include prebuilt libraries for the architecture(s) that you are trying to target.
2.) Can you provide me with a link or a sample of the file you are trying to process?

**Comment by wseemann** [comment]
Closed due to inactivity.
