### ISSUE TITLE
java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF

### ISSUE THREAD

**Issue by shaileshmulange** [wseemann/FFmpegMediaMetadataRetriever#41]
Can I use YouTube Url with FFmpegMediaMetadataRetriever like below code
FFmpegMediaMetadataRetriever retriever = new FFmpegMediaMetadataRetriever();
retriever.setDataSource("http://www.youtube.com/watch?v=Hxy8BZGQ5Jo");

**Comment by wseemann** [comment]
This error message is correct. Your data source is a link to the webpage hosting the video, not a link to the video itself.

**Comment by faizrehman1** [comment]
setDataSource failed: status = 0xFFFFFFFF why Https Url is not supporting .. ??
