### ISSUE TITLE
Get list of I-Frame Times

### ISSUE THREAD

**Issue by spragucm** [wseemann/FFmpegMediaMetadataRetriever#42]
I've been reading the source code for a while now and have  not found a method for retrieving a list of I-Frame times. Basically, I am trying to restrict the times that can be input to mediaPlayer.seekTo(int) based off the I-Frame times. Is this currently possible? If not currently possible, could it be possible in the future?

**Comment by wseemann** [comment]
I looked into this functionality and coded it. However, I wouldn't recommend this approach because it requires reading and parsing the entire file, which is time consuming. If you require this functionality I may be able to provide it as side work but I don't really see the value of adding a function like this to the library.

**Comment by spragucm** [comment]
Thank you for coding this. If you don't recommend this method, do you have another recommendation for limiting the seekTo times so that a user cannot seekTo a time between IFrames? The problem is Android's mediaPlayer, and even the FFmpegMediaPlayer, get out of sync or just kind of go wonky when a video doesn't have IFrames or when mediaPlayer.seekTo is called with a time that is between IFrames. It'd be nice to allow the user to seek and then snap to an IFrame so that everything stays well synchronized.

**Comment by wseemann** [comment]
As I said, if you want to contact me about doing side work then we may be able to arrange something. I don't want to add this functionality to the library because I don't think it is within the scope of the project or a widely desired feature.
