### ISSUE TITLE
cannot get meta data from a sample movie 

### ISSUE THREAD

**Issue by haozwang618** [wseemann/FFmpegMediaMetadataRetriever#44]
Hi, I am new to android and I am extracting frames from a sample movie in the asset folder that is of format mp4. I installed the ffmpeg where fmmr.jar in the libs folder and the .so files in the /main/src/jniLibs folder. I am testing it on samsung galaxy note 4 phone.

my code is as the following
 metaRetriver = new FFmpegMediaMetadataRetriever();
            AssetFileDescriptor afd = getResources().getAssets().openFd("sampleMovie.mp4");

           // afd = getResources().getAssets().openFd("sampleMovie.mp4");

             String[] ma= getResources().getAssets().list("");
             for( int i =0; i < ma.length; ++i)
             {
             Log.i(TAG,ma[i]);
             }

            metaRetriver.setDataSource(afd.getFileDescriptor(),afd.getStartOffset(),afd.getLength());
            Log.i(TAG, "movie starts at " + afd.getStartOffset() + " with length "+ afd.getLength());
            millis =(int) Long.parseLong(metaRetriver.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION));
            now = 0;
            Log.i(TAG, "movie is " + millis + " millisecond longs");
            Log.i(TAG, "movie is " + metaRetriver.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION) + " millisecond longs");
            Log.i(TAG, "movie file size is " + metaRetriver.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_FILESIZE));
            Log.i(TAG, "movie video codec is" + metaRetriver.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_VIDEO_CODEC));
            Log.i(TAG, "movie frame rate is " + metaRetriver.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_FRAMERATE));
            Log.i(TAG, "movie chapter start time is" + metaRetriver.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_CHAPTER_START_TIME));

the result I got from the log
03-23 13:52:56.008  10559-10559/com.example.haozwang.cardboardtheater I/MainActivity﹕ images
03-23 13:52:56.008  10559-10559/com.example.haozwang.cardboardtheater I/MainActivity﹕ sampleMovie.mp4
03-23 13:52:56.008  10559-10559/com.example.haozwang.ct I/MainActivity﹕ sounds
03-23 13:52:56.008  10559-10559/com.example.haozwang.ct I/MainActivity﹕ webkit
03-23 13:52:56.008  10559-10559/com.example.haozwang.ct I/MainActivity﹕ webkitsec
03-23 13:52:56.383  10559-10559/com.example.haozwang.ct I/MainActivity﹕ movie starts at 1168 with length 9287731
03-23 13:52:56.383  10559-10559/com.example.haozwang.ct I/MainActivity﹕ movie is 0 millisecond longs
03-23 13:52:56.383  10559-10559/com.example.haozwang.ct I/MainActivity﹕ movie is 0 millisecond longs
03-23 13:52:56.383  10559-10559/com.example.haozwang.ct I/MainActivity﹕ movie file size is -38
03-23 13:52:56.383  10559-10559/com.example.haozwang.ct I/MainActivity﹕ movie video codec isnull
03-23 13:52:56.383  10559-10559/com.example.haozwang.ct I/MainActivity﹕ movie frame rate is null
03-23 13:52:56.383  10559-10559/com.example.haozwang.ct I/MainActivity﹕ movie chapter start time isnull

the program obviously found the movie file. but the metadataretriever is not getting the data. did I load the .so file wrong?

**Comment by wseemann** [comment]
Can you email me the sample movie so I can test myself?

**Comment by haozwang618** [comment]
okay, email sent. I tried it on both the device and emulators. same error when the file is clearly found by the code...

**Comment by haozwang618** [comment]
after our email exchange I was able to load from SD card, and get the metadata. However; when I started to extract frames from the movie all of them are black. what is going on?

**Comment by wseemann** [comment]
Send me your code, I can't see what you are doing wrong without it.

**Comment by wseemann** [comment]
After checking your file against the command line version of FFmpeg it appears to be corrupted. Running:

cat movie.mp4 | ffmpeg -i pipe:0 -analyzeduration 2147483647 -probesize 2147483647

yields:

`Could not find codec parameters for stream 0 (Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 392 kb/s): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options`

The max allowable probesize is: 2147483647
