### ISSUE TITLE
getFrameAtTime returning the same frame

### ISSUE THREAD

**Issue by maxandron** [wseemann/FFmpegMediaMetadataRetriever#45]
Hello,

What I'm trying to do, is capture a video and then play it frame-by-frame.
The way I decided to do this is load the video into your library, and using a SeekBar change the "Preview" image.

The first problem I encountered was the duration I received was always 0. After playing around with this for a little bit, I found that the library returns only duration in multiplications of a thousand. (0-1000-2000-etc).

When I try getting frames using getFrameAtTime - I get the same frame and not actual frames from the video.

At first I thought the problem was relating to the video being time lapsed (using setCaptureRate) - but after removing this option it didn't change much.
When pulling the video to my computer it plays fine and recognized as MPEG format.

What could be the problem?

Here is the extraction code:
```java
// Set the media player with the video
final FFmpegMediaMetadataRetriever metadataRetriever =
        new FFmpegMediaMetadataRetriever();
final SeekBar videoSeek = (SeekBar) view.findViewById(R.id.video_seek);
videoSeek.bringToFront();

Log.d(TAG, mMediaFilepath);
metadataRetriever.setDataSource(mMediaFilepath);
String duration = metadataRetriever
        .extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_DURATION);

Log.d(TAG, "Duration = " + duration);
mediaPreview.setImageBitmap(metadataRetriever.getFrameAtTime(0));

videoSeek.setMax(Integer.parseInt(duration));

// Set the seek bar actions
videoSeek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
    @Override
    public void onProgressChanged(SeekBar seekBar, int progress,
                                  boolean fromUser) {
        Bitmap bm2 = metadataRetriever.getFrameAtTime();
        Bitmap bm = metadataRetriever.getFrameAtTime(progress,
                FFmpegMediaMetadataRetriever.OPTION_CLOSEST);
        if (bm == null || bm2 == null) {
            Log.e(TAG, "bm is null");
        }
        mediaPreview.setImageBitmap(bm);
    }

    @Override
    public void onStartTrackingTouch(SeekBar seekBar) {
    }

    @Override
    public void onStopTrackingTouch(SeekBar seekBar) {
    }
});
```
One thing to note:
the function never return's a null value - just the same bitmap all over again.

Thank you,
Ron.

P.S.: Here is a link to the video just in case it will help you: https://drive.google.com/file/d/0B50D54gw1jgHT25rQ0ZuRFc5cFk/view?usp=sharing

**Comment by skonb** [comment]
This is very confusing, but getFrameAtTime takes Us instead of ms for time parameter, so you may success by passing progress*1000 for it.

**Comment by maxandron** [comment]
Yes I tried that, but still the same frame is showing.
I'm going another way now, but I would still love to hear a solution in case it helps someone else

**Comment by wseemann** [comment]
As skonb said, you aren't passing the correct unit of time to `getFrameAtTime`. If you are still having problems please email me a link to the file in question so I can test myself.

**Comment by maxandron** [comment]
And as I said, I tried passing everything *1000 and it made no difference.

**Comment by wseemann** [comment]
As I said, send me a link to the video so I can test myself, otherwise I
have no way of debugging your issue.

**Comment by maxandron** [comment]
I did attach a link in the first post.

**Comment by clementiano9** [comment]
> As skonb said, you aren't passing the correct unit of time to `getFrameAtTime`. If you are still having problems please email me a link to the file in question so I can test myself.

Please what is the actual time unit the method should receive?
