### ISSUE TITLE
Is it possible to play .h264 video from amazon s3 server using your library?

### ISSUE THREAD

**Issue by srajesh529** [wseemann/FFmpegMediaMetadataRetriever#47]
I have bunch of .h264 video files in amazon s3 server,my requirement is directly play from url not downloading the video to sd card.is it possible your library?

Thanks in advance

**Comment by wseemann** [comment]
The following code will accomplish what you are asking:
    
    FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
    mmr.setDataSource("amazon URL");
    // ... extract metadata or frames
    mmr.release();

**Comment by srajesh529** [comment]
how to extract the metadata or frames?please provide any sample for this.

**Comment by wseemann** [comment]
https://github.com/wseemann/FFmpegMediaMetadataRetriever#usage
