### ISSUE TITLE
https protocal is supported or not?

### ISSUE THREAD

**Issue by srajesh529** [wseemann/FFmpegMediaMetadataRetriever#49]
Hi,

I have video's in amazon server,below is the sample url format
https://s3.amazonaws.com/XXXXX/filename.h264.
my requirement is getting the first frame of the video, is it possible to get first frame using your library? i am using the http in my video url it successfully get the first frame.but my video url's are https.
how to get first frame using https protocal?

Thanks

**Comment by wseemann** [comment]
https support is disabled by default. To enable support add the prebuilt https libs to your project: https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/master/fmmr-library/prebuilt-libs-with-https.tar.gz
