### ISSUE TITLE
IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF

### ISSUE THREAD

**Issue by nameryan** [wseemann/FFmpegMediaMetadataRetriever#51]
when i set the youtube video url ,not web page url like https://www.youtube.com/watch?v=xxxx, but the real play url extracted with http://en.savefrom.net . it gives IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF.
but i can play this url use MediaPlayer.setDataSource

for example ,the url extracted with  http://en.savefrom.net is
-----------------------------------------------------------------------------------------------------------
http://r7---sn-jou-btxe.googlevideo.com/videoplayback?pl=22&id=o-AJYQBflVIOwEzGgtfDVfBURQtmIn0udbioZQfqhpLS_U&mv=m&mt=1431399289&ms=au&itag=18&ip=200.125.221.138&mm=31&ipbits=0&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Csource%2Cupn%2Cexpire&fexp=907263%2C916660%2C916732%2C934954%2C936118%2C9405265%2C9406543%2C9407992%2C9408142%2C9408706%2C9408979%2C9409061%2C9412533%2C9412858%2C9413105%2C945137%2C948124%2C952612%2C952637%2C952642&source=youtube&dur=127.825&sver=3&ratebypass=yes&signature=8F06B928A67470358092E5BFB7DC9304B167FC13.DB90CC8DD1778DF9D2011EA0A24FC516F1B82C7C&initcwndbps=805000&pcm2cms=yes&key=yt5&mime=video%2Fmp4&expire=1431420985&upn=WqsFWJXv-oY&title=Official+Call+of+Duty%C2%AE-+Black+Ops+III+Reveal+Trailer
-----------------------------------------------------------------------------------------------------------
notice this real url is time limited use

**Comment by wseemann** [comment]
This is a constraint within FFmpeg, the URL is too long. See issue: https://trac.ffmpeg.org/ticket/2976. I verified that shortening the URL fixes the issue.

**Comment by nameryan** [comment]
It's not the long URL issue , the url above is less than 1024.
but i found it works when i add the library into my project ,not just test in the demo project from this git.
