### ISSUE TITLE
FFmpegMediaMetadataRetriever is not working on Samasung GT-S7562

### ISSUE THREAD

**Issue by shaileshmulange** [wseemann/FFmpegMediaMetadataRetriever#52]
I have tried to use FFmpegMediaMetadataRetriever  for capture frame from a video it's working properly for some device but not working on Samsung GT-S7562. It's throwing exception Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1286]:   112 cannot locate '__aeabi_ldiv0'...

**Comment by shaileshmulange** [comment]
Hi, did you found a solution for your problem?

**Comment by Mindbowser** [comment]
Facing same issue, please fix it asap.

**Comment by wseemann** [comment]
This is fixed in the latest release, v1.0.6.
