### ISSUE TITLE
extractMetadataFromChapter not working

### ISSUE THREAD

**Issue by Ph1b** [wseemann/FFmpegMediaMetadataRetriever#53]
How can I extract metadata from a chapter? It takes two parameters, one is the metadata to extract and one is the index? How can I know how many indexes are there?

And should the chapters not be included in what getMetadata() returns? I have a m4b file, where ffmpeg on linux shows chapters, but your mediametadataretriever does not. What is the correct way to extract start, end and chapternames?

**Comment by Ph1b** [comment]
I used sample files from [auphonic](https://auphonic.com/blog/2013/07/03/chapter-marks-and-enhanced-podcasts/)
and
````java   
String time1 = mmr.extractMetadataFromChapter(FFmpegMediaMetadataRetriever.METADATA_KEY_CHAPTER_START_TIME, 0);
````
returns ````null

**Comment by wseemann** [comment]
This is fixed in the latest release, the demo application also now includes code to retrieve the corresponding metadata from files that contain chapters.
