### ISSUE TITLE
IllegalArgumentException while capturing video frame with youtube url

### ISSUE THREAD

**Issue by amrit-sbagga** [wseemann/FFmpegMediaMetadataRetriever#54]
Hi wseemann,

I am getting IllegalArgumentException while capturing video frame with youtube url on below line :

mmr.setDataSource(videoFilePath, new HashMap<String, String>());

where videoFilePath I am using is : https://www.youtube.com/watch?v=rsTQuxoAflc

Below is stacktrace from logcat:

java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF 
06-01 14:50:05.421: W/System.err(30072): 	at wseemann.media.FFmpegMediaMetadataRetriever._setDataSource(Native Method)
06-01 14:50:05.421: W/System.err(30072): 	at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(FFmpegMediaMetadataRetriever.java:162)

I have included all prebuilt-libs-with-https in my project but I don't know where I am doing it wrong. Kindly help me.

**Comment by wseemann** [comment]
You are receiving an IllegalArgumentException because the URL you provided is a link to the page hosting the video, not a link to the video itself.

**Comment by amrit-sbagga** [comment]
Thank you got it now :)
