### ISSUE TITLE
Get last frame

### ISSUE THREAD

**Issue by Zo2m4bie** [wseemann/FFmpegMediaMetadataRetriever#56]
I have a stream and I want to get new frame every 5 seconds. I tried to use getFrameAtTime() after that I called wait(5000) and after that I called getFrameAtTime() again. In second  getFrameAtTime() I received frame which follows after first frame(which I recieved when call getFrameAtTime at first time). After that I tried to get frame all the time (via getFrameAtTime(-1, FFmpegMediaMetadataRetriever.OPTION_NEXT_SYNC)) and update imageview every 5 second. But I also have some delay because sometime getFrameAtTime work long(once I had difference in time in 5 min). Is it possible to get last video frame?

**Comment by wseemann** [comment]
Try:

```
while (<condition to break loop>) {
    FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
    mmr.setDataSource(<stream URL>);
    Bitmap b = mmr.getFrameAtTime(); // current frame
    mmr.release();
    
    //Pause for 5 seconds 
    Thread.sleep(5000);
}
```
