### ISSUE TITLE
Specify Architectures

### ISSUE THREAD

**Issue by Nutomic** [wseemann/FFmpegMediaMetadataRetriever#58]
The project currently includes about 30 MB of native code for 4 different architectures. Is there any way to exclude some of these for reduced apk size?

I'm using the project as a gradle dependency.

**Comment by wseemann** [comment]
I just added prebuilt AARs for each architecture: https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/master/prebuilt-aars.zip?raw=true
