### ISSUE TITLE
setDataSource failed: status = 0xFFFFFFFF

### ISSUE THREAD

**Issue by guensuanhoa** [wseemann/FFmpegMediaMetadataRetriever#59]
I have 175 mp4 files. When I process file from index 0 to index 65 (or 66), I get exception:

```
java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF
at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(Native Method)
at com.jni.utils.Mp4ParserUsingFFMpeg.createThumbnail(Mp4ParserUsingFFMpeg.java:518)
at com.example.readmdtfile.activity.MainActivity$createMp4Async.createThumbnail(MainActivity.java:71)
at com.example.readmdtfile.activity.MainActivity$createMp4Async.doInBackground(MainActivity.java:55)
at com.example.readmdtfile.activity.MainActivity$createMp4Async.doInBackground(MainActivity.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
```
If I run process from index 65 (or nearby), processing file 65 is successful. But it still get exception sometimes
Here is code which i'm using:
```
	public static Bitmap createThumbnail (String videoPath) {
		FFmpegMediaMetadataRetriever retriever = new  FFmpegMediaMetadataRetriever();
		Bitmap bitmap = null;
		try {
			retriever.setDataSource(videoPath); //file's path
			String key;
			String value;
			for (int i = 0; i < MetadataKey.METADATA_KEYS.length; i++) {
    			key = MetadataKey.METADATA_KEYS[i];
    			value = retriever.extractMetadata(key);
    			if (value != null) {
    				// metadata.add(new Metadata(key, value));
    				Log.i(TAG, "Key: " + key + " Value: " + value);
    			}
    		}
			
			bitmap = retriever.getFrameAtTime();
			
			if (bitmap != null) {
				Log.d(TAG, "Extracted frame");
    			Bitmap b2 = retriever.getFrameAtTime(4000000,
    					FFmpegMediaMetadataRetriever.OPTION_CLOSEST_SYNC);
    			if (b2 != null) {
    				bitmap = b2;
    			}
    		} else {
    			Log.d(TAG, "Failed to extract frame");
    		}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			retriever.release();
		}

		return bitmap;
	}
```
Please help me.

**Comment by Zo2m4bie** [comment]
I have the same problem. Did you find out how to fix it?

**Comment by guptasanchit90dev** [comment]
Did you add the permissions in the Manifest file

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_SETTINGS" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

**Comment by guensuanhoa** [comment]
I already added those permissions in the Manifest file, but i still got this error.

**Comment by wseemann** [comment]
Why don't you print out the URI path causing the issue and try to retrieve
metadata from that one file individually?

**Comment by guensuanhoa** [comment]
At first, I thought this file is corrupted data. But when I start process from this file (index 65 or 66), this process successful. => this file is not corrupted data.

Then I try to release some variable in native code but it is not feasible. Now I using function get thumbnail which is provided by android. But i don't understand some device (samsung device) can not get thumbnail from some video.

**Comment by ThoughtPT** [comment]
I'm trying to retrieve a image from a frame of a video using FFmpegMediaMetadataRetriever

this is the code im using: the variable path has this value "https://s3-us-west-2.amazonaws.com/avnohellodev/videos/9e867aba83197862e7500ebe3ebfd68a.mp4"

```
new Thread(new Runnable() {
                    public void run() {

                        try {
                            FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
                            mmr.setDataSource(path);
                            final Bitmap b = mmr.getFrameAtTime(2000000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST); // frame at 2 seconds
                            mmr.release();

                            video_thumb.post(new Runnable() {
                                public void run() {
                                    video_thumb.setImageBitmap(b);
                                }
                            });
                        }catch (java.lang.IllegalArgumentException e){
                            e.printStackTrace();

                        }
                    }
                }).start();
```

when the code reaches the setDataSource i also get

    java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF

Anything wrong with my code, or is this video not supported for some reason ?

**Comment by wseemann** [comment]
@ThoughtPT use the prebuilt AAR's with HTTPS support found [here](https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/master/prebuilt-aars-with-https.zip?raw=true).

**Comment by fxpage** [comment]
@wseemann I have same issue.
But the url you have supported is not working.
Please let me know where can I find the prebuilt AAR's with HTTPS.

**Comment by BenjaminWegener** [comment]
https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/download/v1.0.14/prebuilt-aars-with-https.zip

**Comment by chathura123456** [comment]
The error is simple, an RuntimeException means the video URI is invalid. Verify the valid Video URI with .mp4 format, before attempting to use it with FFmpegMediaMetadataRetriever.

ImageView thumbnail1 = (ImageView) findViewById(R.id.video1); thumbnail1.setImageBitmap(retriveVideoFrameFromVideo("http://techslides.com/demos/sample-videos/small.mp4"));

public Bitmap retriveVideoFrameFromVideo(String videoPath) {

    Bitmap bitmap = null;
    MediaMetadataRetriever mediaMetadataRetriever = null;
    try {
        mediaMetadataRetriever = new MediaMetadataRetriever();
        if (Build.VERSION.SDK_INT >= 14)
            mediaMetadataRetriever.setDataSource(videoPath, new HashMap<String, String>());
        else
            mediaMetadataRetriever.setDataSource(videoPath);
        //   mediaMetadataRetriever.setDataSource(videoPath);
        bitmap = mediaMetadataRetriever.getFrameAtTime(1, MediaMetadataRetriever.OPTION_CLOSEST);
    } catch (Exception e) {
        e.printStackTrace();
        Toast.makeText(getApplicationContext(), e.getMessage(), Toast.LENGTH_LONG).show();
    } finally {
        if (mediaMetadataRetriever != null) {
            mediaMetadataRetriever.release();
        }
    }
    return bitmap;
}

**Comment by RowlandOti** [comment]
Also happens, if you run out of memory. The native code is so inefficient and can quickly lead to an OOM if inefficient java/Koltin code is written on top of it.

**Comment by marioneahsay** [comment]
Still happens to me when I use headers on setDataSource even when using prebuilt aars instead of gradle dependencies. I'm only testing using one remote video url - http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4 

`private static Bitmap getBitmapAtTime ( String filePath, int time, Map headers) {
        FFmpegMediaMetadataRetriever retriever = new FFmpegMediaMetadataRetriever();
        if (URLUtil.isFileUrl(filePath)) {
            retriever.setDataSource(Uri.decode(filePath).replace("file://", ""));
        } else {
            if (Build.VERSION.SDK_INT < 14) {
                throw new IllegalStateException("Remote videos aren't supported on sdk_version less than 14");
            }
            if (headers.isEmpty()) {
                retriever.setDataSource(filePath);
            } else {
                retriever.setDataSource(filePath, headers);
            }
        }  

        Bitmap image = retriever.getFrameAtTime(time * 1000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST);
        retriever.release();
        if (image == null) {
            throw new IllegalStateException("File doesn't exist or not supported" + filePath);
        }
        return image;
    }`

Is this library still being maintained? There are a lot of questions related to this topic but with no reply.

**Comment by wseemann** [comment]
@marioneahsay I don't maintain this project as actively as I used to but I will look into your issue this weekend and get back to you. Thanks for your patience!

**Comment by AndreyMolochko** [comment]
I have the same problem and I have tested on different videos and I see some logic of this error. I always get this error when I make request for videos, which started from "https"
If I use "http" It's ok
@wseemann I hope my information helps you fix this issue

**Comment by NeighborhoodCoding** [comment]
Hi, My path(mUri) is "androud.resource://org.appname/raw/video1"
and I got same error, 0xFFFFFFF error comes out...

In my app, there is raw folder and video1.mp4
How should I change my mUri?
