### ISSUE TITLE
library too big when compile

### ISSUE THREAD

**Issue by Alakeel** [wseemann/FFmpegMediaMetadataRetriever#60]
I added the dependency to my application ( build.gradle ) in my Android Stuido 

The apk jumped from 2 MB to 16 MB ! 

I just used the sample code nothing more ,, is there a way to have a less size than this ! ?

I used 
FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();
mmr.setDataSource(mUri);
mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ALBUM);
mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ARTIST);
Bitmap b = mmr.getFrameAtTime(2000000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST); // frame at 2 seconds
byte [] artwork = mmr.getEmbeddedPicture();

mmr.release();

**Comment by wseemann** [comment]
I I just added prebuilt AARs for each architecture: https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/master/prebuilt-aars.zip?raw=true
