### ISSUE TITLE
get messy code when extract metadata from mp3 with japanese character in title

### ISSUE THREAD

**Issue by cmnewfan** [wseemann/FFmpegMediaMetadataRetriever#62]
code is like this:
mediaMetadataRetriever = new FFmpegMediaMetadataRetriever();
        Uri uri = Uri.fromFile(FileActivity.currentPlayingFile);
        mediaMetadataRetriever.setDataSource(context,uri);
        String title = mediaMetadataRetriever.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_TITLE);

but the metatdata i get is like this:
�Ĥ����
i've tried to convert the code from utf-8 to gbk,the code is like this:
String utf8Title = mediaMetadataRetriever.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_TITLE);
        utf8Title = new String(utf8Title.getBytes(""),"UTF-8");
gbkTitle = URLEncoder.encode(utf8Title,"ISO-8859-1");

but it did not work, is there a way to fix this problem?

**Comment by cmnewfan** [comment]
I've also tried this:
Metadata metadata = mediaMetadataRetriever.getMetadata();
        byte[] array = metadata.getByteArray("title");
        gbkTitle = new String(array,"GBK");

it didn't work either

**Comment by wseemann** [comment]
Do you have a file I can test with?

**Comment by mhcpan** [comment]
Hi,
Example link: http://sv1.ezyradio.net:9000/
Same issue as cmnewfan reported. It is a Thailand radio station.

**Comment by mhcpan** [comment]
Hi,
Another streaming url with Chinese Characters metadata cannot be displayed correctly.

http://192.241.214.243:8394

**Comment by wseemann** [comment]
The links you provided did not work for me. I'm unable to test/reproduce the issue. Closed due to inactivity.
