### ISSUE TITLE
FFmpegMediaMetadataRetriever returns setDataSource failed: status = > 0xFFFFFFFF

### ISSUE THREAD

**Issue by alirezaaa** [wseemann/FFmpegMediaMetadataRetriever#63]
This is a weird error! because it sometimes works but sometimes doesn't work. I'm using this library to get the thumbnail from a video using an URL path. `retriever.setDataSource(((Video) obj).getVideoAddress());` return following error: 

> java.lang.IllegalArgumentException: setDataSource failed: status =
> 0xFFFFFFFF

**This is my code:**

    FFmpegMediaMetadataRetriever retriever = new FFmpegMediaMetadataRetriever();
                Bitmap bmp;
    
                retriever.setDataSource(((Video) obj).getVideoAddress
                        ());
    
                bmp = retriever.getFrameAtTime();

**Note:** I checked the INTERNET permission and it exists. The problem is exists with some videos but with the same format! I mean the only difference between videos is bit rates, length, size and others like this but not the file format.

  [1]: https://github.com/wseemann/FFmpegMediaMetadataRetriever

**Comment by wseemann** [comment]
What URL are you using?

**Comment by alirezaaa** [comment]
@wseemann I'm using URLs like following:`http://192.168.1.121:16905/Uploads/Videos/1.mp4`

**Comment by wseemann** [comment]
This URL doesn't help me since it's local, I can't test with it. Do you have an external URL I can use?

**Comment by LubomyrShershun** [comment]
confirmed. 
 Url:
https://ia700401.us.archive.org/19/items/ksnn_compilation_master_the_internet/ksnn_compilation_master_the_internet_512kb.mp4
Log:
E/AndroidRuntime:  Caused by: java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF
E/AndroidRuntime:     at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(Native Method)

**Comment by wseemann** [comment]
I just tried this URL, FFmpegMediaMetadataRetriever works as expected using the current prebuilt AAR's with HTTPS.
