### ISSUE TITLE
Videos accessible with MediaMetadataRetriever() but not FFmpegMediaMetadataRetriever()

### ISSUE THREAD

**Issue by timsee** [wseemann/FFmpegMediaMetadataRetriever#64]
Hey,

I'm trying to convert my project from using MediaMetadataRetriever to FFmpegMediaMetadataRetriever for the added flexibility and speed of ffmpeg. For some reason, videos that can be accessed by MediaMetadataRetriever cannot be accessed by FFmpegMediaMetadataRetriever. I'm storing the videos locally and using a method like this to access it:

```
 final AssetFileDescriptor afd = mContext.getResources().openRawResourceFd(R.raw.testvideo);
 mRetriever.setDataSource(afd.getFileDescriptor(), afd.getStartOffset(), afd.getLength());
```

I get the setDataSource failed error: status => 0xFFFFFFFF message.

I've tried converting to using URIs with methods like this:

```
 Uri uri = Uri.parse("android.resource://com.test.videobitmapper/" + R.raw.testvideo);
 mRetriever.setDataSource(uri.toString());
```

 but I still get identical errors. I'm using android studio and targeting SDKVersion 22, if that could be the cause of the issue. I'm trying to access an .mp4. 

Any ideas as to what I can try?

**Comment by pawlusmall** [comment]
Same issue for me

**Comment by Vangaorth** [comment]
Same here

**Comment by drbeermann** [comment]
I'm seeing something similar as well and haven't been able to find a workaround. If I set the data source with a URI I get the 0xffffffff error, but if I set it with a file descriptor as you are above, then I can set the data source but getFrameAtTime returns null. The same URI works fine with MediaMetadataRetriever.

**Comment by drbeermann** [comment]
Well, I ended up solving my problem by using the precompiled aar (all-fmmr). I still got a null Bitmap from getFrameAtTime when using the file descriptor, but it works using the URI, not sure why there's a difference there.

**Comment by jerry33** [comment]
@wseemann Is this issue fixed, please? I've been trying to get it working whole day, but still getting `0xffffffff` error, RuntimeException when using `setDataSource()` method...

**Comment by chan1600** [comment]
I think you are not able to read the file inside Assert folder.
Try to put the video in external directory
Environment.getExternalStorageDirectory() will give u the external directory path.
Also, you will need to get uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" in manifests

**Comment by hamzashahid91** [comment]
same issue can get it working with android.permission.READ_EXTERNAL_STORAGE
