### ISSUE TITLE
METADATA_KEY_ALBUM retrieving artist sort order tag

### ISSUE THREAD

**Issue by cwbowron** [wseemann/FFmpegMediaMetadataRetriever#66]
I just integrated this library into my project, and it's working great, except instead of the album title, it seems to be retrieving the artist sort name.

For example, with Michael Jackson "Thriller" tracks the results are:

METADATA_KEY_ARTIST: "Michael Jackson"
METADATA_KEY_ALBUM: "Jackson, Michael"

I double checked with a command line version of FFmpeg and it is reading the values correctly.

Checked and didn't see any issues opened for this.

**Comment by cwbowron** [comment]
Note: I'm using the maven version: 

compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.1'

**Comment by cwbowron** [comment]
Doing some more digging, it looks like it might be returning ALBUMARTISTSORT instead of album in this case. This is the result of dumping getMetadata().getAll(). The album is showing up in the meta data map, so I can easily work around the bug for now.

album_artist: Michael Jackson
TIPL: producer
ALBUMARTISTSORT: Jackson, Michael
MusicBrainz Album Status: official
MusicBrainz Album Artist Id: f27ec8db-af05-4f36-916e-3d57f91ecf5e
artist-sort: Jackson, Michael
album: Thriller
track: 9/9
MusicBrainz Album Id: 959272f9-97ae-4179-aebe-950eef64ed93
date: 1982
audio_codec: mp3
publisher: Epic
filesize: 7186432
duration: 299000
title: The Lady in My Life
ASIN: B0000025RI
MusicBrainz Album Type: album
MusicBrainz Album Release Country: US
artist: Michael Jackson
MusicBrainz Artist Id: f27ec8db-af05-4f36-916e-3d57f91ecf5e
CATALOGNUMBER: QE-38112

**Comment by wseemann** [comment]
Can you email me the track so I can test locally?

**Comment by wseemann** [comment]
Fixed in latest release, thank you for reporting this issue.
