### ISSUE TITLE
Trying to get MetaData of mp3 files from cloud, error 

### ISSUE THREAD

**Issue by marinica94** [wseemann/FFmpegMediaMetadataRetriever#67]
I am trying to retrieve metadata of a mp3 file from cloud.
Caused by: java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF

mmr.setDataSource(String.valueOf(Uri.parse(curentURL)));
                    String artist = mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ARTIST);
                    String title = mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_TITLE);

Any ideea how can I solve this ? 

https://storage-c1.rcs-rds.ro/content/files/get/Fox+Stevenson+-+All+This+Time.mp3?base=MTQ0NTIzOTQzNnxwaWdMRmI3STczM0Z4eEdRLVdMek1jc2dkQTltcUR3MlNJaUQ3VDhDOEE1R1dLVE5sTjl5VE1icWJBX0k0ektMcHZnckFMa181cnVEcTlpM2RFanZGZ3QzZHRqY2tPX0pRdlhRd0Y4N1hsOExrSEJjbTFHOTZkV25LTF9nXzJVdUdJRG9lZkdsa1hDYTNoZ0xFR1dESTVPcmF2RUtiVjRmQjMwai0wZ19mSHhlZ0J5cWZsenQ3NlV6VWNWS2dUbGRtd0hMdXlTMmVrd0d4V1FMWDhLdXRCN1QwRV9pN1Jub2hsRzBSUy11WHBQM20tMjRUdC1rNWhLM3lnYzRfdEhIX0VtZ1lsaHoyWHpXR3BudWRVdEVoUT09fIF7iCULcSRZbs98ioXErJvfUvKnqUtmAhokNuhr2yko

**Comment by wseemann** [comment]
Use the prebuilt AARs (with HTTPS support) found [here] (https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/master/prebuilt-aars-with-https.zip).
