### ISSUE TITLE
IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF

### ISSUE THREAD

**Issue by mhcpan** [wseemann/FFmpegMediaMetadataRetriever#68]
Hi,
I used FMMRDemo with the following URL:
http://listen.radionomy.com/animeradionet.m3u
Error triggered when using FFmpegMediaMetadataRetriever for above link.

If analysis the m3u file, we get the following link:
http://streaming.radionomy.com/AnimeRadioNet
Metadata can be retrieved with the above link.

Is it mean that FFmpegMediaMetadataRetriever cannot support m3u format?

**Comment by wseemann** [comment]
FFmpegMediaMetadataRetriever does not support m3u files. You will need to parse the entries before passing them to `setDataSource`.
