### ISSUE TITLE
Frame always null with bytedeco/javacv 1.1

### ISSUE THREAD

**Issue by gouravd** [wseemann/FFmpegMediaMetadataRetriever#71]
I have been using javacv 1.0. Since fmmr has its own libavcodec.so etc.. I used the following config in Android Studio build.gradle to use javacv 1.0's corresponding .so files

pickFirst 'lib/armeabi-v7a/libavcodec.so'
        pickFirst 'lib/armeabi-v7a/libavformat.so'
        pickFirst 'lib/armeabi-v7a/libavutil.so'
        pickFirst 'lib/armeabi-v7a/libswscale.so'
        pickFirst 'lib/armeabi-v7a/libswresample.so'

Everything worked fine until I upgraded to javacv 1.1. When I use the javacv v1.1's so files, Frame is always returned null.

Bitmap frame = metaRetriever.getFrameAtTime(1000000);

**Comment by wseemann** [comment]
You are using javacv .so files, this is not a bug with the actual library.
