### ISSUE TITLE
metadata not changing

### ISSUE THREAD

**Issue by permenko** [wseemann/FFmpegMediaMetadataRetriever#73]
Hi,
I'm trying to retrieve metadata from icecast radio (http://boorime.com:8000/boorime)

Here's my code:
//I initialized FFmpegMediaMetadataRetriever
mmr = new FFmpegMediaMetadataRetriever();
mmr.setDataSource("http://boorime.com:8000/boorime");
and then repeat mmr.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_ICY_METADATA)
every 5 sec to detect new track, but it's not working.

Metadata is updated only after I call mmr.setDataSource, but it's cost me about 300kB.
I can not afford it

**Comment by wseemann** [comment]
Sorry, FFmpeg does not retrieve new metadata until a new context is created. Calling `setDataSource` each time is the only way to retrieve updated metadata.
