### ISSUE TITLE
Changing signature of lib to show frame on SurfaceView

### ISSUE THREAD

**Issue by Zo2m4bie** [wseemann/FFmpegMediaMetadataRetriever#75]
Is it possible to change signature of your lib to frames will be transmitted to SurfaceView? It will be like little video player. I need to show 4 video stream without audio, I tried to use your lib. App draws frame(which it receives via getFrame) on surfaceview but it's kind of slow.

**Comment by wseemann** [comment]
Added in version 1.0.4.
