### ISSUE TITLE
`getFrameAtTime` produce bitmap in different orientation.

### ISSUE THREAD

**Issue by ayublin** [wseemann/FFmpegMediaMetadataRetriever#76]
Firstly, thanks for making this great library available, works way more accurate than Android's `MediaMetadataRetriever`.

So, I got a video which height is bigger than the width (portrait), I ran `getFrameAtTime` to the video, but, the produced bitmap is a -90 degree rotated version of the video which is making it landscape.

It's not happening with Android's `MediaMetadataRetriever`, is there any way for me to get the method to produce bitmap with the same orientation as the video?

Thanks.

**Comment by ChristopheCVB** [comment]
+1

**Comment by wseemann** [comment]
Can you provide a sample URL to test with?

**Comment by wseemann** [comment]
Closed due to inactivity.

**Comment by hardikJoshi123** [comment]
+1

**Comment by HBiSoft** [comment]
@wseemann in my issue #190 I provided how to reproduce this issue.

**Comment by HBiSoft** [comment]
@hardikJoshi123 Where you able to resolve this issue? I managed to find a workaround but I would like to know how others fixed this issue.
