### ISSUE TITLE
How to import aar file to Eclipse?

### ISSUE THREAD

**Issue by sunshinetpu** [wseemann/FFmpegMediaMetadataRetriever#77]
Hi. I download prebuilt-aars folder and copy all the aar files to the libs folder of my project. Then in my code I tried to call FFmpegMediaMetadataRetriever. But Eclipse didn't suggest anything. I think I missed something.

**Comment by wseemann** [comment]
Eclipse support has been discontinued in favor of Android Studio. Please migrate your project.
