### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by zhangchenghaigithub** [wseemann/FFmpegMediaMetadataRetriever#79]
Error:Execution failed for task ':library:buildFFmpeg'.
> A problem occurred starting process 'command 'E:\FFmpegMediaMetadataRetriever-master\gradle\fmmr-library\library\src\main\scripts\build-ffmpeg.sh''

**Comment by zhangchenghaigithub** [comment]
看看这是什么情况

**Comment by wseemann** [comment]
This is fixed in the latest version (v1.0.5).

**Comment by raytona** [comment]
I have same problem in the latest version (Import libarary module)
