### ISSUE TITLE
Sample app crashes when loading movie from HTTP

### ISSUE THREAD

**Issue by Inx51** [wseemann/FFmpegMediaMetadataRetriever#80]
Hi!
Been having some issues getting started with this lib (might have missed something).. however.. I just tried the pre-built .apk against the following url:
http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4
The app crashes once I hit "Go"

Any ideas?

**Comment by wseemann** [comment]
Fixed in version 1.0.4.
