### ISSUE TITLE
libavcodec.so has text relocations

### ISSUE THREAD

**Issue by lupin78** [wseemann/FFmpegMediaMetadataRetriever#81]
Hi,

I have an error on android 6 when i instantiate : 
`FFmpegMediaMetadataRetriever mmr = new FFmpegMediaMetadataRetriever();`

I get this message : 
`E/linker﹕ /data/app/com.arsprod.frich-1/lib/arm/libavcodec.so: has text relocations
 java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.arsprod.frich-1/lib/arm/libavcodec.so: has text relocations`

I am using 1.0.2 version
`compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.2'`

**Comment by wseemann** [comment]
Fixed in latest version (v1.0.4).
