### ISSUE TITLE
SetDataSource don't working on AOSP Android 4.1\4.2\6.0

### ISSUE THREAD

**Issue by dante2130** [wseemann/FFmpegMediaMetadataRetriever#84]
SetDataSource has exception when calling it on devices with android versions in title. 

This caused in demo application, after click "Load" and test video link placed in textView:

`02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err: java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(Native Method)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at wseemann.media.demo.MetadataLoader.loadInBackground(MetadataLoader.java:64)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at wseemann.media.demo.MetadataLoader.loadInBackground(MetadataLoader.java:37)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:128)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-13 17:14:16.669 1130-2271/wseemann.media.fmpdemo W/System.err:     at java.lang.Thread.run(Thread.java:856)
`

What do you think about this? Thanks in advance.

**Comment by wseemann** [comment]
The error speaks for itself: `java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF`. This means the input source was incorrect.
