### ISSUE TITLE
The lib throw  Fatal signal 11

### ISSUE THREAD

**Issue by Zo2m4bie** [wseemann/FFmpegMediaMetadataRetriever#85]
Hi, I receive fatal signal in my app.

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xf1c in tid 7461 (Thread-277)

It reproduce very simple.

Code:

```
public class MainActivity extends AppCompatActivity implements Runnable{

    private boolean running;
    private Thread thread;
    int count;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @Override
    protected void onResume() {
        super.onResume();
        running = true;
        thread = new Thread(this);
        thread.start();
    }

    @Override
    protected void onPause() {
        super.onPause();
        running = false;
    }

    @Override
    public void run() {
        FFmpegMediaMetadataRetriever retriver;
        count = 0;
        while(running){
            retriver = new FFmpegMediaMetadataRetriever();
            retriver.setDataSource(STREAM_URL);
            Bitmap b = retriver.getFrameAtTime();
            if(b != null){
                b.recycle();
                b = null;
            }
            retriver.release();
            count++;
            Log.d("DATA", "Count = "+ count);
        }
    }
}

```

On genimotion it throw signal on 157 step, on LG-D415 on 72 step
I use 

    `compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.3'`

I reproduce it on Samsung Galaxy 3(Android 4.3), LG-D415(Android 5.0.2) and also I reproduced it on genimotion nexus 5(Android 5.1)

**Comment by wseemann** [comment]
Please post a full stack trace.

**Comment by wseemann** [comment]
Try with version (v1.0.5).

`compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.5'`

**Comment by Zo2m4bie** [comment]
No, new version 1.0.6 didn't help, It still fails. About stack trace, I have only fatal signal
```

04-03 15:31:14.416 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: native_setup
04-03 15:31:14.416 1687-1732/wseemann.media.demo V/MediaMetadataRetrieverJNI: setDataSource
04-03 15:31:14.938 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:14.939 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: native_setup
04-03 15:31:14.939 1687-1732/wseemann.media.demo V/MediaMetadataRetrieverJNI: setDataSource
04-03 15:31:15.458 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:15.459 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: native_setup
04-03 15:31:15.459 1687-1732/wseemann.media.demo V/MediaMetadataRetrieverJNI: setDataSource
04-03 15:31:16.030 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:16.031 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: native_setup
04-03 15:31:16.031 1687-1732/wseemann.media.demo V/MediaMetadataRetrieverJNI: setDataSource
04-03 15:31:16.558 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:16.559 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: native_setup
04-03 15:31:16.559 1687-1732/wseemann.media.demo V/MediaMetadataRetrieverJNI: setDataSource
04-03 15:31:17.085 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:17.090 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: native_setup
04-03 15:31:17.090 1687-1732/wseemann.media.demo V/MediaMetadataRetrieverJNI: setDataSource
04-03 15:31:17.806 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:17.809 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: native_setup
04-03 15:31:17.809 1687-1732/wseemann.media.demo V/MediaMetadataRetrieverJNI: setDataSource
04-03 15:31:18.456 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:18.457 1687-1732/wseemann.media.demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x409 in tid 1732 (Thread-173)
```


But sometime I see a lot of release log one by one, maybe it will help

`04-03 15:31:12.147 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: native_setup
04-03 15:31:12.147 1687-1732/wseemann.media.demo V/MediaMetadataRetrieverJNI: setDataSource
04-03 15:31:12.724 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:12.725 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: native_setup
04-03 15:31:12.725 1687-1732/wseemann.media.demo V/MediaMetadataRetrieverJNI: setDataSource
04-03 15:31:13.284 1687-1732/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.285 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.286 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.286 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release
04-03 15:31:13.286 1687-1699/wseemann.media.demo I/MediaMetadataRetrieverJNI: release`

**Comment by wseemann** [comment]
Please try version 1.0.9:

```
dependencies {
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.9'
}
```

**Comment by Hackmodford** [comment]
I get the same error message. The getEmbeddedPicture line seems to cause the crash.

```
try {
            final byte[] art = mmr.getEmbeddedPicture();
            track.artwork = BitmapFactory.decodeByteArray(art, 0, art.length);
        } catch (Exception e) {
            e.printStackTrace();
            //Logger.e(LOGTAG, "Couldn't create album art: " + e.getMessage());
        }
```

I am also using version 1.0.9

**Comment by wseemann** [comment]
What error message? Your code snippet contains no stack trace.

**Comment by Hackmodford** [comment]
Does this help?

`05-27 20:19:09.056 9766-9766/com.hackmodford.bigfinish W/ActivityThread: Application com.hackmodford.bigfinish is waiting for the debugger on port 8100...
05-27 20:19:09.056 9766-9766/com.hackmodford.bigfinish I/System.out: Sending WAIT chunk
05-27 20:19:09.191 9766-9776/com.hackmodford.bigfinish I/art: Debugger is active
05-27 20:19:09.257 9766-9766/com.hackmodford.bigfinish I/System.out: Debugger has connected
05-27 20:19:09.257 9766-9766/com.hackmodford.bigfinish I/System.out: waiting for debugger to settle...
05-27 20:19:09.457 9766-9766/com.hackmodford.bigfinish I/System.out: waiting for debugger to settle...
05-27 20:19:09.657 9766-9766/com.hackmodford.bigfinish I/System.out: waiting for debugger to settle...
05-27 20:19:09.858 9766-9766/com.hackmodford.bigfinish I/System.out: waiting for debugger to settle...
05-27 20:19:10.058 9766-9766/com.hackmodford.bigfinish I/System.out: waiting for debugger to settle...
05-27 20:19:10.258 9766-9766/com.hackmodford.bigfinish I/System.out: waiting for debugger to settle...
05-27 20:19:10.459 9766-9766/com.hackmodford.bigfinish I/System.out: waiting for debugger to settle...
05-27 20:19:10.659 9766-9766/com.hackmodford.bigfinish I/System.out: debugger has settled (1338)
05-27 20:19:10.688 9766-9766/com.hackmodford.bigfinish I/ContextImpl: com.amazon.client.metrics.api registered service at i = 69
05-27 20:19:10.850 9766-9766/com.hackmodford.bigfinish D/ProfileManager: Create ProfileManager instance
05-27 20:19:11.077 9766-9776/com.hackmodford.bigfinish W/art: Suspending all threads took: 10.413ms
05-27 20:19:11.622 9766-9766/com.hackmodford.bigfinish W/linker: libswscale.so: unused DT entry: type 0x6ffffffe arg 0xd4c
05-27 20:19:11.622 9766-9766/com.hackmodford.bigfinish W/linker: libswscale.so: unused DT entry: type 0x6fffffff arg 0x1
05-27 20:19:11.623 9766-9766/com.hackmodford.bigfinish W/linker: libavcodec.so: unused DT entry: type 0x6ffffffe arg 0x5150
05-27 20:19:11.623 9766-9766/com.hackmodford.bigfinish W/linker: libavcodec.so: unused DT entry: type 0x6fffffff arg 0x1
05-27 20:19:11.625 9766-9766/com.hackmodford.bigfinish W/linker: libavformat.so: unused DT entry: type 0x6ffffffe arg 0x504c
05-27 20:19:11.625 9766-9766/com.hackmodford.bigfinish W/linker: libavformat.so: unused DT entry: type 0x6fffffff arg 0x2
05-27 20:19:11.628 9766-9766/com.hackmodford.bigfinish W/linker: libffmpeg_mediametadataretriever_jni.so: unused DT entry: type 0x6ffffffe arg 0x26ac
05-27 20:19:11.628 9766-9766/com.hackmodford.bigfinish W/linker: libffmpeg_mediametadataretriever_jni.so: unused DT entry: type 0x6fffffff arg 0x4
05-27 20:19:11.629 9766-9766/com.hackmodford.bigfinish I/MediaMetadataRetrieverJNI: native_init
05-27 20:19:11.630 9766-9766/com.hackmodford.bigfinish I/MediaMetadataRetrieverJNI: native_setup
05-27 20:19:11.631 9766-9766/com.hackmodford.bigfinish V/MediaMetadataRetrieverJNI: setDataSource
05-27 20:19:11.808 9766-9766/com.hackmodford.bigfinish A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 9766 (dford.bigfinish)`

**Comment by wseemann** [comment]
Yes, thank you. Can you also let me know what version of Android you are
using and, if possible, email me the file or link you are testing with?

**Comment by Hackmodford** [comment]
Testing with Android API 22
The file will take a while for me to upload, my internet sucks. I will upload overnight and email you a link tomorrow.

Thank you for the help!

**Comment by Hackmodford** [comment]
Email has been sent.

**Comment by Hackmodford** [comment]
The files I'm testing are m4b. Could that be the problem?

**Comment by wseemann** [comment]
@Hackmodford

I believe I fixed the issue. Please try version 1.0.10:

```
dependencies {
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.10'
}
```

**Comment by Hackmodford** [comment]
For some reason, it seems like Android Studio can't find the update.

`Failed to resolve: com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.10`

**Comment by wseemann** [comment]
Sorry, it's fixed now.

**Comment by Hackmodford** [comment]
This seems to have fixed my problem.
