### ISSUE TITLE
How to use latest upgrade for Eclipse?

### ISSUE THREAD

**Issue by shaileshmulange** [wseemann/FFmpegMediaMetadataRetriever#90]
Earlier I have used the fmmr.jar file for FFmpegMediaMetadataRetriever but after Android 6.0 (Marshmallow) is coming this is not working so I want to upgrade my jar file for Android 6.0  so how to integrate the latest update with Eclipse.

**Comment by wseemann** [comment]
Eclipse is deprecated and this project no longer supports it.
