### ISSUE TITLE
 compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.4' not working.

### ISSUE THREAD

**Issue by shaileshmulange** [wseemann/FFmpegMediaMetadataRetriever#91]
I have used  "compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.4'" in my build.gradle file but still given a error "can not resolved FFmpegMediaMetadataRetriever".

i.e.dependencies {
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.4'
}
Please suggest me I need to add something more or it's sufficient.

**Comment by wseemann** [comment]
Please try version 1.0.6:

```
dependencies {
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.6'
}
```
