### ISSUE TITLE
I use 1.0.6 in studio Android, the device for the Samsung S6 Edge GALAXY and  Samsung Galaxy Note5 , out of the error 

### ISSUE THREAD

**Issue by wodedaxue0609** [wseemann/FFmpegMediaMetadataRetriever#94]
The following is the error code:
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-support-annotations-locSDK_6.13_915915e595a3f4ba459c898e1b3feb7e1dc4980d-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-internal_impl-23.3.0_7a5b347e7336aab56dd1804c3a4fecea75c1dd9b-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-gson-2.4_99df27fd41a157555d5140048df875de27228204-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-cyberplayer-sdk_97cf323e3cebb0c9a89dea3af4f1ab2d87603722-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-com.jiechic.library-xUtils-2.6.14_f4ee3e3502679fe240b66048f0edad72d2520acc-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-com.android.support-support-v4-23.3.0_5b0d870942acbddf1c58a9c4b9ff2bd3e13e9f84-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-com.android.support-appcompat-v7-22.2.1_af600d282ad2b6939de037f4175775435c0ed1a8-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-baidumapapi_search_v3_7_3_a704cfbed3fcba0c165461d1ba4415f84696eb43-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-baidumapapi_map_v3_7_3_760c5dc72d95b7ef192ee0ae3734b4c08cb5b98f-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-baidumapapi_base_v3_7_3_962c9f894c42d19d2af4b5a09892e65354fcad62-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-ShareSDK-Wechat-Moments-2.7.1_427f809028db6e1d0531b6aa17178d3dd148fb69-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-ShareSDK-Wechat-Favorite-2.7.1_eb54a218f6f88e316745702e77a27c94d2064798-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-ShareSDK-Wechat-Core-2.7.1_9eb25ea96fda80bbcab917917cffb71291ec8c34-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-ShareSDK-Wechat-2.7.1_da6eef78bf8cef44439f13dd7a292cf98a060e16-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-ShareSDK-SinaWeibo-2.7.1_c134e5ab6206c101e08890165a4e8308557121b5-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-ShareSDK-QQ-2.7.1_11cec577e2745d314dc4f762735ad04c1a4f0103-classes.dex", dex file "/data/data/com.bjanch.www.mobilemonitoring/files/instant-run/dex/slice-ShareSDK-Core-2.7.1_8

**Comment by wseemann** [comment]
I don't see any error in this log that relates to this library.

**Comment by hsy402** [comment]
I have same issue. Did you solve this problem?
