### ISSUE TITLE
Another getting null value for METADATA_KEY_VIDEO_ROTATION

### ISSUE THREAD

**Issue by vxhviet** [wseemann/FFmpegMediaMetadataRetriever#95]
Hi @wseemann, thanks again for your awesome library.

First of all, I'm able to extract the video orientation out of [this video](https://www.dropbox.com/s/d4lgfh8h0vqzzyw/Gallus_3.mp4?dl=0) captured by my Nexus 5 using the Android's native `MediaMetadataRetriever` like this:

```java
MediaMetadataRetriever m = new MediaMetadataRetriever();
        m.setDataSource(mVideoPath);

        if (Build.VERSION.SDK_INT >= 17) {
            String s = m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_ROTATION);
            return s;
        }
        return null;
```

However, this method return null for [this video](https://www.dropbox.com/s/ew12ly1cfmwol77/iOs%20Video.mp4?dl=0) which is captured by an iPhone 6s.

So I try to use `FFmpegMediaMetadataRetriever`. Unfortunately, it return null for both videos. My code is as below:

```java
FFmpegMediaMetadataRetriever m = new FFmpegMediaMetadataRetriever();
        m.setDataSource(mVideoPath);

        try{
            String s = m.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_VIDEO_ROTATION);
            return s;
        }catch (Exception e){
            e.printStackTrace();
        }

        return null;
```

What do you think is the possible solution for this problem?

**Comment by wseemann** [comment]
@vxhviet use the prebuilt AAR's with HTTPS support found [here](https://github.com/wseemann/FFmpegMediaMetadataRetriever/blob/master/prebuilt-aars-with-https.zip?raw=true).

**Comment by vxhviet** [comment]
I can't say how much I love you @wseemann, you literally solve all of my problems with one stone.

I will make a donation as long as I receive this month paycheck.

Again  thank you for your hard work.

**Comment by vxhviet** [comment]
However, the this built still hasn't been able to extract the Rotation of the iPhone [video](https://www.dropbox.com/s/ew12ly1cfmwol77/iOs%20Video.mp4?dl=0). 

What do you think is the main culprit here?

**Comment by vxhviet** [comment]
Funny observation after trying both prebuilt AAR and prebuilt AAR with HTTPS:

prebuilt aars: all-fmmr, armv7-fmmr
- landscape videos not working.
- portrait video working.

prebuilt aars with https: all-fmmr, armv7-fmmr
- landscape videos not working.
- portrait video working.

No worries though, I'll keep using the `MediaMetadataRetriever` for now.

**Comment by wseemann** [comment]
When you say "not working" do you mean it just doesn't retrieve the
rotation or it won't retrieve any metadata or frames?

**Comment by vxhviet** [comment]
Using `FFmpegMediaMetadataRetriever`:
```java
FFmpegMediaMetadataRetriever m = new FFmpegMediaMetadataRetriever();
        m.setDataSource(mVideoPath);

        try{
            String s = m.extractMetadata(FFmpegMediaMetadataRetriever.METADATA_KEY_VIDEO_ROTATION);
            return s;
        }catch (Exception e){
            e.printStackTrace();
        }

        return null;
```
`s` is 90 for portrait video and null for landscape video.

 Using `MediaMetadataRetriever `, `s` is 90 for portrait and 0 for landscape video.

I haven't tested any other metadata so I can't tell.

Frame retrieval works fine, only the `METADATA_KEY_VIDEO_ROTATION` gives problem.

**Comment by wseemann** [comment]
@vxhviet This should now be fixed in the [latest release](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.7). Please let me know if this fixes your issue.

**Comment by vxhviet** [comment]
Hi @wseemann, thanks you for your effort.

Good news is this version can extract `METADATA_KEY_VIDEO_ROTATION` out of iOS video so it's no longer `null`.

Bad news is for both portrait and landscape video, it always return 0. Below is my observation:

- Using `compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.7`: successfully retrieve `METADATA_KEY_VIDEO_ROTATION`, however:

  - Landscape video: s = 0 (correct)
  - portrait video: s = 0 (incorrect should be 90)
  - iOS landscape video: s = 0 
  - iOS portrait video: s = 0 (incorrect should be 90)

- Using *prebuilt-aars-with-https*:
  - all-fmmr.aar: same result

- Using *prebuilt-aars*:
  - all-fmmr.aar: same result

**Comment by wseemann** [comment]
Can you send me one of each to test, one portrait video and one landscape?

**Comment by vxhviet** [comment]
In [this file](https://www.dropbox.com/s/wt1jonmfnns4flf/Videos.zip?dl=0), there are 2 iOS and 2 Android videos captured by the iPhone 6s and Nexus 5.

I would like to ask, besides the `METADATA_KEY_VIDEO_ROTATION`, is there any performance improve for frame extraction in version 1.0.7?

**Comment by wseemann** [comment]
Ok, I'll verify against these videos, sorry for the regression bug. This
version only included the rotation fix, no other improvements.

**Comment by vxhviet** [comment]
No worries, thank you for putting all your effort in bug fixing :+1:

**Comment by wseemann** [comment]
This should be fixed in version [1.0.8](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.8).

**Comment by vxhviet** [comment]
Confirmed working, you're golden @wseemann.  

This is completely irrelevant but if you have any experience on this matter, I would love to hear. I use Glide to load the thumbnail of videos into `ImageView`, it works fine for Android video but return blank for iOS videos. My theory is iOS using an abnormal encoder for its video which also giving `FFmpegMediaMetadataRetriever` some trouble. I wonder during fixing these bugs, would you have come across these same problems?

**Comment by vxhviet** [comment]
Hi @wseemann, just a quick question. How do you do the calculation for `METADATA_KEY_VIDEO_ROTATION` as when I'm trying to use `ffprobe` to display my video's metadata, there's no field for rotation or orientation whatsoever? 

Something like this:

`ffprobe -show_streams file.mp4`

**Comment by wseemann** [comment]
Some videos have this metadata field and some don't. If the video doesn't have the field then the key would return null. There isn't any real calculation being performed.

**Comment by vxhviet** [comment]
Yes, thats why I'm scratching my head because I'm using the same video. Your FFMR is able to retrieve this value while the ffprobe's output show nothing.

**Comment by vxhviet** [comment]
I think i know why now. Only 90 or 270 video (portrait video) has this field.

**Comment by HBiSoft** [comment]
Hi @vxhviet 
I have the same issue. Up until now, I have been using `MediaMetadataRetreiver` to extract a Bitmap from a video and then use that Bitmap to determine the rotation of the video.

This was working well on most devices, but I have noticed that on some devices `MediaMetadataRetreiver` fails. Currently, I'm searching for an alternative.

Can you please tell me what you ended up doing/using?

**Comment by vxhviet** [comment]
It's been a long time since I worked on this project so I don't quite remember what I used. But basically you have 2 options outside of this:
- ExoPlayer: powerful library but also have a lot of unnecessary stuff for your purpose.
- a newer Prebuilt FFmpeg library: building ffmpeg lib yourself could be a tedious process so I recommend find a prebuilt one. FFmpeg is very powerful, support even more video type than ExoPlayer.

Side Note: extracting bitmap to detect rotation sounds suboptimal, you would better rely on metadata for this purpose.

**Comment by HBiSoft** [comment]
@vxhviet 
Thank you for your response.

I currently have a Prebuilld FFmpeg library included in my project, but how would I use FFmpeg to determine the rotation of a video file? I would have to use FFprobe for that, wouldn't I?

**Comment by vxhviet** [comment]
You would need a version that allow you to execute command line, something like this lib:

https://github.com/bravobit/FFmpeg-Android

after that, you just execute normal FFmpeg command. This FFmpegMediaMetadataRetriever lib is already an implementation of FFmpeg so maybe check around which one have a newer FFmpeg version/

**Comment by HBiSoft** [comment]
@vxhviet 
I have that library implemented into my project already but I'm not aware that FFmpeg can provide me with the video dimensions or rotation? AFAIK I have to use FFprobe for that.

I'm also using the latest `FFmpegMediaMetadataRetriever` prebuild aar's.

**Comment by vxhviet** [comment]
Correct, you will need ffprobe to get that data, something like this (https://superuser.com/questions/660505/find-out-rotation-metadata-from-video-in-ffmpeg). You will need to check if the quoted library support that.

Also, when I said the version of the library I mean the version of FFmpeg that the library built upon, not the version of the library itself.

**Comment by HBiSoft** [comment]
@vxhviet 
But including FFprobe increases my application size drastically (just to find the rotation of a video).

Also, I understood what you said about the versioning but I don't think it will help me get a video's dimentions.
