### ISSUE TITLE
libhoudini.so is missing

### ISSUE THREAD

**Issue by almozavr** [wseemann/FFmpegMediaMetadataRetriever#96]
`UnsatisfiedLinkError: dlopen failed: library "/system/lib/libhoudini.so` occurs on `API<21` since `1.0.4`

**Comment by wseemann** [comment]
What device are you testing on? This library doesn't require or need access to libhoudini.so.

**Comment by almozavr** [comment]
It occurs on `Genymotion` and some other devices gives warning (but not an error).
`1.0.3` gives no error on `Genymotion` as well.
```
E/dalvikvm: dlopen("/data/app-lib/io.techery.spoiq.pro-2/libswscale.so") failed: dlopen failed: library "/system/lib/libhoudini.so" not found
W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lwseemann/media/FFmpegMediaMetadataRetriever;
```

**Comment by wseemann** [comment]
I don't currently support testing on `Genymotion`. Have you tried [this](http://www.rajatswarup.com/blog/2015/02/24/genymotion-and-libhoudini-so-error/).

**Comment by almozavr** [comment]
@wseemann with `translation` installed another error occured:
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stpcpy" referenced by "libffmpeg_mediametadataretriever_jni.so"
...
at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(FFmpegMediaMetadataRetriever.java:124)
```

Anyway, it seems nothing to do with Retriever-lib itself, so closing the issue.
Thanks for support!
