### ISSUE TITLE
Generate signed apk failed

### ISSUE THREAD

**Issue by JeremyLam1** [wseemann/FFmpegMediaMetadataRetriever#97]
i just locally used your project two aars , which are arm-fmmr.aar and armv7-fmmr.aar . then i want to generate signed apk, but failed! 
   there is the error:
            "Duplicate zip entry [classes.jar:wseemann/media/BuildConfig.class]"

**Comment by wseemann** [comment]
This is fixed in the latest [release](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases).
