### ISSUE TITLE
How to pipe the FFmpeg output to a Surface or a Bitmap?

### ISSUE THREAD

**Issue by vxhviet** [wseemann/FFmpegMediaMetadataRetriever#99]
Dear @wseemann, sorry for troubling you again.

While using the FMMR to retrieve a frame with something like this:

`Bitmap b = mmr.getFrameAtTime(position*1000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST);` 

I notice the retrieving time is quite long (about 1748 milliseconds). I've tracked down the method until I hit `private native byte [] _getFrameAtTime(long timeUs, int option);` and I can't really tell for sure which method you use to retrieve the frame.

When using [FFmpeg-Android-Java](https://github.com/WritingMinds/ffmpeg-android-java) to run FFmpeg input seeking like this:

`-ss 00:00:01.015 -i input.mp4 -frames:v 1 out1.jpg` 

I can get the frame in about 1174 milliseconds. And this is for a normal Android video. For a well indexed video which has a key frame for every 2 frames (something like frame I, frame P, frame I,...), the performance is slightly better. Please see the tables below:

| Normal Video   |                   |
|----------------|-------------------|
| FMMR           | 1748 milliseconds |
| FFmpeg seeking | 1174 milliseconds |

| Well indexed Video   |                   |
|----------------|-------------------|
| FMMR           | 820 milliseconds |
| FFmpeg seeking | 730 milliseconds |

I know the bottleneck for the FFmpeg seeking command is the output has to be written in the memory so it would take time. For FFMR as the output is a `Bitmap`, I could not tell for sure is there any disk writing/ reading involved that could possibly affect the performance.

I would like to ask you is there a possible way to piping the output of your FFmpeg process to a `Surface` or a `Bitmap` directly so we could hopefully improve the performance.

**Comment by wseemann** [comment]
Yes, it is possible, use
http://wseemann.github.io/FFmpegMediaMetadataRetriever/apidocs/wseemann/media/FFmpegMediaMetadataRetriever.html#setSurface(java.lang.Object)

**Comment by vxhviet** [comment]
Here is how I use the `setSurface` method:

```java
@Override
    public void surfaceCreated(SurfaceHolder holder) {
        //test new stuff
        mFFmpegMediaMetadataRetriever = new FFmpegMediaMetadataRetriever();
        mFFmpegMediaMetadataRetriever.setDataSource(mVideoPath);
        mFFmpegMediaMetadataRetriever.setSurface(holder.getSurface());
        mFFmpegMediaMetadataRetriever.getFrameAtTime(currentVideoPosition*1000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST); //position in MICROseconds
    }
```

And use this to do the seeking:

```java
public void update(){
        if(canSeek){
            new AsyncTask(){
                long start;
                long end;

                @Override
                protected void onPreExecute() {
                    super.onPreExecute();
                    canSeek = false;
                    start = System.currentTimeMillis();
                }

                @Override
                protected Object doInBackground(Object[] params) {
                    mFFmpegMediaMetadataRetriever.getFrameAtTime(currentVideoPosition*1000, FFmpegMediaMetadataRetriever.OPTION_CLOSEST); //position in MICROseconds
                    return null;
                }

                @Override
                protected void onPostExecute(Object o) {
                    super.onPostExecute(o);
                    canSeek = true;
                    end = System.currentTimeMillis();
                    Log.d(TAG, "Seek in: " + (end - start) + " milliseconds");
                }
            }.execute();
        }
}
```

It takes about 1000 - 2000 milliseconds for normal video and 900 - 1000 milliseconds for the well indexed video. So basically, it still doing the same thing but the result is pushed to the `Surface` automatically?

**Comment by wseemann** [comment]
Correct, it is pushed automatically.

**Comment by vxhviet** [comment]
In your `getFrameAtTime` method, is there any disk read/ write operation involved? What I would like to achieve is somehow piping the `FFmpeg` output directly into the `Surface`. Is that even possible? I would like to make sure before diving in all the pain of creating my FFmpeg player just to realize it's not even possible.

**Comment by wseemann** [comment]
I'm not sure what you mean. The method I just provided is draws the
re-encoded frame directly on to the Surface. If you avoid using
OPTION_CLOSEST seeking will be much faster.
